### ISSUE TITLE
Wabbajack not checking if file exists after "Trying to find solution to broken download"

### ISSUE THREAD

**Issue by mvaraine** [wabbajack-tools/wabbajack#1268]
Hi,

Wabbajack doesnt seem to check if the file exists after going thru its  "Trying to find solution to broken download ..." routine, causing it to download the file even if present.

Cheers

**Comment by EzioTheDeadPoet** [comment]
If it is broken then this could mean 2 things:

1. The already downloaded file is broken, WJ needs to redownload.
2. The link is broken WJ will need to find an alternative, WJ will download a file if successful.

So I am am not sure what you issue is.

Wabbajack checks before downloading which files are already there and which are missing, so if it tries to download a file then that file is missing.

**Comment by mvaraine** [comment]
number 2:

47.72 - Downloading Project Clarity - Clutter Half Res-43401-1-0-1608487048.7z
48.05 - File hash check (-42) 208d8114262df30784814735d7140c0cba17e7bbcebf817ed9b351a754c8db64
49.01 - File hash check (-42) 208d8114262df30784814735d7140c0cba17e7bbcebf817ed9b351a754c8db64
49.97 - Nexus call failed `https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/43401/files/175402/download_link.json`: Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 23
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\NexusApi\NexusApi.cs:line 264
51.72 - Error reading https://mirror.wabbajack.org:443/e8a81995cfba0018/definition.json.gz retrying [1]
51.72 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 126
51.87 - Error reading https://mirror.wabbajack.org:443/e8a81995cfba0018/definition.json.gz retrying [2]
51.87 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 126
51.94 - Error reading https://mirror.wabbajack.org:443/e8a81995cfba0018/definition.json.gz retrying [3]
51.95 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 124
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Http\Client.cs:line 24
   at Wabbajack.Lib.Downloaders.WabbajackCDNDownloader.State.GetWithCDNRetry(Client client, String url, Nullable`1 token) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\WabbajackCDNDownloader.cs:line 126
52.13 - Trying CDN...
53.06 - Trying to find solution to broken download for Project Clarity - Clutter Half Res-43401-1-0-1608487048.7z
55.25 - Downloading possible upgrade NexusDownloader+State|SkyrimSpecialEdition|43401|177245

I downloaded the 'solution' archive manually and put it in Wabbajacks download folder.

**Comment by EzioTheDeadPoet** [comment]
It was with a 99.9% certainty an updated version of the file you put there and WJ needs the exact version.

**Comment by mvaraine** [comment]
Ok, I'll see if it happens with any other files and test again. Thank you :)
