### ISSUE TITLE
Stream was too long error

### ISSUE THREAD

**Issue by m-vlad** [wabbajack-tools/wabbajack#1390]
**Describe the bug**

When installing my modlist, Wabbajack spews at an error near the end of the installation when copying inlined files along the lines of `Stream was too long`. The modlist (for testing on your side) can be found [here](https://drive.google.com/file/d/1qHXRUSI23bCJwuJh0o1SO3SPRpxncKvi/view?usp=sharing). [I found a similar issue on stackoverflow already, it might be helpful](https://stackoverflow.com/questions/39834634/failed-to-write-large-amount-of-data-to-stream).

**Additional Context**

Windows 10 19042 64 Bit, Skyrim VR.

**Wabbajack Version**

v2.4.3.1 (also present on 2.4.2.7) with the latest exe.

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/6206145/Wabbajack.current.log)
The error bit:
```
2301.98 - Encountered error, can't continue - System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.IO.FileStream.AsyncModeCopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Wabbajack.Common.Utils.ReadAllAsync(Stream ins) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 296
   at Wabbajack.Common.Utils.ReadAllAsync(Stream ins) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 296
   at Wabbajack.Common.AbsolutePath.ReadAllBytesAsync() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Paths\AbsolutePath.cs:line 291
   at Wabbajack.Common.AbsolutePath.ReadAllBytesAsync() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Paths\AbsolutePath.cs:line 291
   at Wabbajack.Lib.AInstaller.LoadBytesFromPath(RelativePath path) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 79
   at Wabbajack.Lib.MO2Installer.<InstallIncludedFiles>b__26_0(InlineFile directive) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 382
   at Wabbajack.Common.Utils.<>c__DisplayClass94_0`1.<<PMap>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 338
--- End of stack trace from previous location ---
   at Wabbajack.Common.Utils.<>c__DisplayClass98_1`1.<<PMap>b__1>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 461
--- End of stack trace from previous location ---
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, Func`2 f) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 478
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, StatusUpdateTracker updateTracker, Func`2 f) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Utils.cs:line 334
   at Wabbajack.Lib.MO2Installer.InstallIncludedFiles() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 359
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 180
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373
```

**Comment by halgari** [comment]
You've somehow managed to inline an entire 2.4GB .zip file into your modlist :

```
    {
      "$type": "InlineFile, Wabbajack.Lib",
      "SourceDataID": "1a691b1d-2acd-4a62-bd71-4f64becd4799",
      "Hash": "XLy8YGSGbas=",
      "Size": 2419572145,
      "To": "mods\\UVREborn 1.3 - Facial Features & Hair\\UVREborn 1.3 - Facial Features & Hair.zip"
    },
```

The installer is complaining because it's not designed to inline files this large.

**Comment by halgari** [comment]
If you need this data as a resource for your list, upload it to a site, then reference it in the installer. That way the `.wabbajack` file remains small.

**Comment by m-vlad** [comment]
I see, it would be good if wabbajack either warned during packing or split the inlined files up into <2gb parts.

**Comment by Timboman** [comment]
@m-vlad I can see why you got confused with that file, since I pre-merged & BSA packed it in base UVRE it's actually these some of the meshes and textures from these mods merged into one big BSA to save on space and loose file clutter:
![image](https://user-images.githubusercontent.com/36910038/112545693-e6ae7f00-8d8e-11eb-9a21-4462438c3592.png)

Meaning that as long as you have those file sources in your downloads you DON'T have to inline anything to use it,

**Comment by m-vlad** [comment]
Well I packed them for performance reasons, since they're likely to be used by npcs, but I'll find a solution at least this is pointing me in the right path.

**Comment by Timboman** [comment]
@m-vlad As long as you have all the proper source files it doesn't matter if you pack them in a BSA or have them Loose, WJ can handle it as needed. I'd recommend doing what I did, have a seperate "mod" just for the BSA files and one for the merged ESP so you ONLY mark the ESP as inlined rather than accidentally inlining textures and meshes you don't need to.
![image](https://user-images.githubusercontent.com/36910038/112546262-9d126400-8d8f-11eb-9bc4-eac37b4935db.png)

**Comment by m-vlad** [comment]
The reason it was inlining 2+ gb is because i made a zip backup of the loose assets and forgot it in the facial features folder... Oh well, at least I found this out. It would be good if the log would be a bit more descriptive, so I can debug it better or find out where i messed something up. did you find that stuff in the manifest?
