### ISSUE TITLE
v2.5.1.2 Cannot login to LL through the client on Win8.1

### ISSUE THREAD

**Issue by Kryomancer** [wabbajack-tools/wabbajack#1533]
**Describe the bug**

Trying to log into LL does not succeed. After entering account information an auth page with empty permissions is shown, choosing to continue will result in a white page that never proceeds.

![https://i.imgur.com/SaOn1p5.png](https://i.imgur.com/SaOn1p5.png)

This appears similar to the issues https://github.com/wabbajack-tools/wabbajack/issues/1515 and https://github.com/wabbajack-tools/wabbajack/issues/1523 but on Discord support channel I was told this is not the case as I'm on Win 8.1 and that it is not possible to implement OAuth2 on Win8.1, so I was recommended to submit a new bug report in hopes of a fix applicable to my use case.

**Additional Context**

Win 8.1

**Wabbajack Version**

2.5.1.2

**Logs**

```
37,71 - Getting Nexus API Key, if a browser appears, please accept
37,79 - Getting Lovers Lab Login
38,24 - Logged into the nexus as redacted
38,24 - Nexus calls remaining: 2500 daily, 100 hourly
46,73 - Scheme Handler Got: wabbajack : wabbajack://loverslab/?code=bca414b2c80f92be9e1220a0f065a50ff83983ade2acdc3b883cdd721d0fb4de&state=e007489d-fc9d-4b89-88fb-49c95c684473
46,73 - Got Scheme callback wabbajack://loverslab/?code=bca414b2c80f92be9e1220a0f065a50ff83983ade2acdc3b883cdd721d0fb4de&state=e007489d-fc9d-4b89-88fb-49c95c684473
51,06 - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.<GetAuthedClient>b__43_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 134
   at Wabbajack.Common.Utils.CatchAndLog(Func`1 f) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Logging.cs:line 163
51,06 - System.Exception: Must log into Lovers Lab to continue
51,07 - File hash check (-42) cad10838cf9315ae2a59b4578ba516bcf0f347cbffe92acf5ed1ebb3b0e55f59
51,19 - Encountered error, can't continue - System.Exception: Must log into Lovers Lab to continue
   at Wabbajack.Common.Utils.ErrorThrow(Exception ex, String extraMessage) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Common\Logging.cs:line 109
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.GetAuthedClient() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 137
   at Wabbajack.Lib.Downloaders.AbstractIPS4OAuthDownloader`2.Prepare() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\AbstractIPS4OAuthDownloader.cs:line 124
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 212
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 138
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
51,27 - File hash check (-42) cad10838cf9315ae2a59b4578ba516bcf0f347cbffe92acf5ed1ebb3b0e55f59
```

**Comment by halgari** [comment]
I'm sorry but Wabbajack is only supported on Windows 10, we're also seeing this functionality only working on recent Windows 10 builds (about 2 years old).
