### ISSUE TITLE
Installing of Modlist failed, when file on Mega was missing

### ISSUE THREAD

**Issue by Gyrofalcon** [wabbajack-tools/wabbajack#1735]
**Describe the bug**

Wabbajack app report Installation failed, and the log report points to url https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg and that is removed/gone.

**Additional Context**

Win10

The file you are trying to download is no longer available.
This could be due to the following reasons:
The file has been removed because of a ToS or AUP violation.
Invalid URL - the link you are trying to access does not exist
The file has been deleted by the user.

Shouldn't the modlist installation just continue, with error report in the end? With info of where user must go, to fetch files manually?

**Wabbajack Version**

2.5.3.1

**Logs**

800,77 - Downloading Mod.Organizer-2.4.2.7z
828,61 - Hashing Remaining Archives
828,62 - Looking for files to hash
828,64 - Found 544 total files, 106 matching filesize
828,66 - Unable to download xLODGen.83.7z (MegaDownloader+State|https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg)
828,66 - Cannot continue, was unable to download one or more archives
828,66 - File hash check (-42) 8001fcee66c1f67bd9d230b5cc4d48813f4ad8fc7518a5a3a88b14fa182c0a88
828,67 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
828,88 - File hash check (-42) 8001fcee66c1f67bd9d230b5cc4d48813f4ad8fc7518a5a3a88b14fa182c0a88

**Comment by EzioTheDeadPoet** [comment]
There is a link to the file in the [discord](https://discord.gg/wabbajack) it is pinned in the Wabbajack-Help channel.
