### ISSUE TITLE
Modlist Installation Failed

### ISSUE THREAD

**Issue by anquoc95** [wabbajack-tools/wabbajack#1759]
I try many times but can not make it work . 
i put Wabbajack download in D disk . 
I use windows 10 and Wabbajack version 2.5.3.3.

```

0.19 - Wabbajack Build - f0820514e7dfce84303dde8ef09257bdbbf59c25
0.19 - Running in D:\Wabbajack
0.2 - Detected Windows Version: 10.0.19042.0
0.21 - System settings - (15.4GB RAM) (5GB Page), Display: 1920 x 1080 (5.9GB VRAM - VideoMemorySizeMb=10240)
0.21 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.21 - Outside of standard install folder, not updating
0.22 - Steam: Found no Regex matches in Steam Config at d:/steam\config\config.vdf
0.22 - Steam: Found game Steamworks Common Redistributables (228980) at "D:\Steam\steamapps\common\Steamworks Shared"
0.22 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Steam\steamapps\common\Skyrim Special Edition"
0.22 - Steam: Found game Dota 2 (570) at "D:\Steam\steamapps\common\dota 2 beta"
0.22 - Steam: Found game Black Desert (582660) at "D:\Steam\steamapps\common\Black Desert Online"
0.22 - Steam: Found game Steamworks Common Redistributables (228980) at "d:/steam\steamapps\common\Steamworks Shared"
0.22 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "d:/steam\steamapps\common\Skyrim Special Edition"
0.22 - Steam: Found game Dota 2 (570) at "d:/steam\steamapps\common\dota 2 beta"
0.22 - Steam: Found game Black Desert (582660) at "d:/steam\steamapps\common\Black Desert Online"
0.22 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1495134320 does not have a value BUILDID
0.22 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.22 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.22 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.47 - Wabbajack Version: 2.5.3.3
1.63 - Build server is alive
1.63 - File hash check (-42) 1d886927d24191dd45ff7379084254fe1d87f39ce13ef521902695be5730dd50
1.65 - Build server is alive
1.65 - File hash check (-42) 1d886927d24191dd45ff7379084254fe1d87f39ce13ef521902695be5730dd50
5.33 - Starting to install Dungeons & Deviousness Director's Cut
5.34 - Cleaning VFS, this may take a bit of time
5.38 - Starting Installer Task
5.38 - Installation has Started
5.38 - File hash check (-42) 1d886927d24191dd45ff7379084254fe1d87f39ce13ef521902695be5730dd50
6.79 - Configuring Processor
6.8 - Install Folder: D:\Dungeons & Deviousness
6.8 - Downloads Folder: D:\Dungeons & Deviousness\downloads
6.8 - Game Folder: D:\Steam\steamapps\common\Skyrim Special Edition
6.8 - Wabbajack Folder: D:\Wabbajack
6.8 - Drive watcher is starting. Will warn at 8GB and error at 4GB
6.8 - Starting Drive watcher on D:\ currently 224.7GB free out of 537.1GB
6.8 - Validating Game ESMs
6.82 - Creating Output Folders
7.48 - Optimizing ModList
7.48 - Optimizing ModList directives
9.55 - Looking for files to delete
9.59 - Cleaning empty folders
10.49 - Looking for unmodified files
11.05 - Updating ModList
11.05 - Optimized 231785 directives to 231785 required
11.11 - Hashing Archives
11.11 - Looking for files to hash
11.16 - Found 929 total files, 917 matching filesize
11.33 - Downloading Missing Archives
11.34 - Missing 2 archives
11.34 - Getting Nexus API Key, if a browser appears, please accept
12.42 - Logged into the nexus as gobintechin
12.42 - Nexus calls remaining: 10000 daily, 500 hourly
12.68 - Logged into the nexus as gobintechin
12.68 - Nexus calls remaining: 10000 daily, 500 hourly
12.68 - Loading server whitelist
12.97 - Loaded permissions for 616 servers and 271 Google Drive files
12.97 - File hash check (-42) 1d886927d24191dd45ff7379084254fe1d87f39ce13ef521902695be5730dd50
13.05 - Downloading Sex Lab - Sexual Fame Framework SE V0.99.7z
13.05 - Downloading Firm HDT-SMP Settings - CBBE-42107-1-0-1604728194.zip
13.52 - Loaded page https://loverslab.com//applications/core/interface/file/attachment.php?id=830404 starting download...
13.89 - File hash check (-42) 1d886927d24191dd45ff7379084254fe1d87f39ce13ef521902695be5730dd50
14.11 - Nexus call failed `https://build.wabbajack.org:443/v1/games/skyrimspecialedition/mods/42107/files/168993.json`: Wabbajack.Common.Exceptions.HttpException: Http Error Forbidden - Forbidden
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 100
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 110
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 23
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\NexusApi\NexusApi.cs:line 268
14.12 - Loading for alternative to mpRZJapKYRg=
14.3 - No alternative for mpRZJapKYRg= could be found

```

**Comment by anquoc95** [comment]
problem is solved .
