### ISSUE TITLE
Failed during Hash check happened with both Elysium and Serenity 2

### ISSUE THREAD

**Issue by kiskie** [wabbajack-tools/wabbajack#1815]
39.21 - Starting to install Elysium
39.22 - Cleaning VFS, this may take a bit of time
39.26 - Starting Installer Task
39.26 - Installation has Started
39.27 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
39.47 - Configuring Processor
39.48 - Install Folder: E:\wabbajack\elesyum\downloads\downloads
39.48 - Downloads Folder: E:\wabbajack\elesyum\downloads
39.48 - Game Folder: E:\steam\steamapps\common\Skyrim Special Edition
39.48 - Wabbajack Folder: E:\downloads 2\2.5.3.4
39.48 - Drive watcher is starting. Will warn at 8GB and error at 4GB
39.48 - Starting Drive watcher on E:\ currently 181.8GB free out of 931.4GB
39.48 - Validating Game ESMs
39.51 - Creating Output Folders
39.63 - Optimizing ModList
39.63 - Optimizing ModList directives
43.49 - Looking for files to delete
43.49 - Cleaning empty folders
45.16 - Looking for unmodified files
46.93 - Updating ModList
46.93 - Optimized 241594 directives to 241594 required
46.99 - Hashing Archives
46.99 - Looking for files to hash
47.14 - Found 1570 total files, 1549 matching filesize
47.63 - Downloading Missing Archives
47.63 - Missing 3 archives
47.63 - Getting Nexus API Key, if a browser appears, please accept
47.71 - Loading server whitelist
47.89 - Loaded permissions for 642 servers and 284 Google Drive files
47.9 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
47.93 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
47.95 - Downloading xLODGen.84.7z
47.95 - Downloading Elysium - Core Files.7z
48.15 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
48.31 - Loading for alternative to uq8KT2b+f9A=
48.37 - No alternative for uq8KT2b+f9A= could be found
51.62 - Loading for alternative to Ypeg2MKgzlQ=
51.69 - No alternative for Ypeg2MKgzlQ= could be found
217.76 - Hashing Remaining Archives
217.76 - Looking for files to hash
217.91 - Found 1572 total files, 1550 matching filesize
218.39 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
218.39 - Unable to download Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar (HTTPDownloader+State|https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar)
218.39 - Cannot continue, was unable to download one or more archives
218.39 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
218.41 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
218.7 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
556.71 - Starting to install Elysium
556.74 - Starting Installer Task
556.74 - Installation has Started
556.74 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
556.99 - Configuring Processor
556.99 - Install Folder: E:\wabbajack\elesyum
556.99 - Downloads Folder: E:\wabbajack\elesyum\downloads
556.99 - Game Folder: E:\steam\steamapps\common\Skyrim Special Edition
556.99 - Wabbajack Folder: E:\downloads 2\2.5.3.4
556.99 - Drive watcher is starting. Will warn at 8GB and error at 4GB
557 - Starting Drive watcher on E:\ currently 180.8GB free out of 931.4GB
557 - Validating Game ESMs
557 - Creating Output Folders
557.1 - Optimizing ModList
557.1 - Optimizing ModList directives
560.74 - Looking for files to delete
560.77 - Deleting plugins\game_nehrim.dll it's not part of this ModList
560.77 - Deleting logs\usvfs-2022-01-15_23-49-43.log it's not part of this ModList
560.77 - Deleting logs\mo_interface.log it's not part of this ModList
560.79 - Cleaning empty folders
563.56 - Looking for unmodified files
567.97 - Updating ModList
567.97 - Optimized 241594 directives to 241558 required
568.01 - Hashing Archives
568.01 - Looking for files to hash
568.16 - Found 1572 total files, 1550 matching filesize
568.57 - Downloading Missing Archives
568.57 - Missing 2 archives
568.58 - Getting Nexus API Key, if a browser appears, please accept
568.58 - Loading server whitelist
568.72 - Loaded permissions for 642 servers and 284 Google Drive files
568.72 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
568.79 - Downloading xLODGen.84.7z
568.79 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
568.95 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
569.15 - Loading for alternative to uq8KT2b+f9A=
569.26 - No alternative for uq8KT2b+f9A= could be found
577.21 - Loading for alternative to Ypeg2MKgzlQ=
577.29 - No alternative for Ypeg2MKgzlQ= could be found
577.36 - Hashing Remaining Archives
577.36 - Looking for files to hash
577.52 - Found 1572 total files, 1550 matching filesize
577.98 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
577.98 - Unable to download Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar (HTTPDownloader+State|https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar)
577.98 - Cannot continue, was unable to download one or more archives
577.98 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
577.98 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
578.2 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
713.09 - Starting to install Elysium
713.12 - Starting Installer Task
713.12 - Installation has Started
713.12 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
773.67 - File hash check (-42) eb3c75a102637d653dbaa7f02f28265f82a8dcc2f7016bffba6283750663f391
773.7 - Encountered error, can't continue - Wabbajack.Common.Exceptions.HttpException: Http Error GatewayTimeout - Gateway Time-out
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 131
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 23
   at Wabbajack.Lib.Metrics.Send(String action, String subject) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Metrics.cs:line 81
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 60
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383

**Comment by EzioTheDeadPoet** [comment]
https://discord.gg/wabbajack we can provide support for this issue on the discord.
