### ISSUE TITLE
Cannot continue, was unable to download one or more archives

### ISSUE THREAD

**Issue by ViniciusFXavier** [wabbajack-tools/wabbajack#1901]
**Describe the bug**

Unable to install modpack

Error in logs:
```
405,01 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
405,33 - File hash check (-42) 4bb9dd039633d23f57fb28688860f236874295f67b242204daccb75ee2cbfc3a
```

**Additional Context**

Windows 10 Pro Edition
Version 21H1
OS build 19043.1586
Windows Experience Feature Experience Pack 120.2212.4170.0

Processor Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz 3.60GHz
Installed RAM 16.0 GB (usable: 15.9 GB)

**Wabbajack Version**
**v2.5.3.9**
![image](https://user-images.githubusercontent.com/40774281/159625563-bedfd706-3ed7-42a1-968b-33790ff3941f.png)

**Logs**
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/8329752/Wabbajack.current.log)

**Comment by D0KUSE1** [comment]
This isn't an issue with Wabbajack's code, it's failing because a file could not be downloaded. Try downloading the file manually and putting it into the downloads folder yourself, or if the file is not available wait until the modlist author updates their list. The file that is failing is `Crime and Punishment (v1.1.2)-42857-v1-1-2-1620060207.zip`
