### ISSUE TITLE
Fallout 4 - Life in the Ruins modpack - Hash error and can't download error on Data_Fallout4.esm

### ISSUE THREAD

**Issue by marcelgcom** [wabbajack-tools/wabbajack#1974]
0.27 - Wabbajack Build - 69de8f0e7a23c1b163ca7d158eca963343da3432
0.27 - Running in E:\Wabbajack\2.5.3.22
0.29 - Detected Windows Version: 10.0.19043.0
0.29 - System settings - (15.8GB RAM) (15.4GB Page), Display: 1920 x 1080 (7.8GB VRAM - VideoMemorySizeMb=10240)
0.29 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.31 - Getting new Wabbajack version list
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1158310.acf does not contain a value with key BytesToDownload
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1158310.acf does not contain a value with key BytesDownloaded
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1158310.acf does not contain a value with key BytesToStage
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1158310.acf does not contain a value with key BytesStaged
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1536610.acf does not contain a value with key BytesToDownload
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1536610.acf does not contain a value with key BytesDownloaded
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1536610.acf does not contain a value with key BytesToStage
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_1536610.acf does not contain a value with key BytesStaged
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_212680.acf does not contain a value with key BytesToDownload
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_212680.acf does not contain a value with key BytesDownloaded
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_212680.acf does not contain a value with key BytesToStage
0.33 - Steam: ACF Manifest at D:\SteamLibrary\steamapps\appmanifest_212680.acf does not contain a value with key BytesStaged
0.34 - Steam: Found game L.A. Noire (110800) at "D:\SteamLibrary\steamapps\common\L.A.Noire"
0.34 - Steam: Found game Crusader Kings II (203770) at "D:\SteamLibrary\steamapps\common\Crusader Kings II"
0.34 - Steam: Found game The Witcher: Enhanced Edition (20900) at "D:\SteamLibrary\steamapps\common\The Witcher Enhanced Edition"
0.34 - Steam: Found game Path of Exile (238960) at "D:\SteamLibrary\steamapps\common\Path of Exile"
0.34 - Steam: Found game Sid Meier's Colonization (Classic) (327400) at "D:\SteamLibrary\steamapps\common\Sid Meier's Colonization"
0.34 - Steam: Found game Star Trek Timelines (600750) at "D:\SteamLibrary\steamapps\common\Star Trek Timelines"
0.34 - Steam: Found game Disco Elysium (632470) at "D:\SteamLibrary\steamapps\common\Disco Elysium"
0.34 - Steam: Found game Star Trek Online (9900) at "D:\SteamLibrary\steamapps\common\Star Trek Online"
0.34 - Steam: Found game NORCO Act One Demo (1601150) at "E:\SteamLibrary\steamapps\common\NORCO Demo"
0.34 - Steam: Found game The Elder Scrolls II: Daggerfall (1812390) at "E:\SteamLibrary\steamapps\common\The Elder Scrolls Daggerfall"
0.34 - Steam: Found game Age of Empires II (2013) (221380) at "E:\SteamLibrary\steamapps\common\Age2HD"
0.34 - Steam: Found game The Witcher 3: Wild Hunt (292030) at "E:\SteamLibrary\steamapps\common\The Witcher 3"
0.34 - Steam: Found game The Elder Scrolls Online (306130) at "E:\SteamLibrary\steamapps\common\Zenimax Online"
0.34 - Steam: Found game ARK: Survival Evolved (346110) at "E:\SteamLibrary\steamapps\common\ARK"
0.34 - Steam: Found game Fallout 4 (377160) at "E:\SteamLibrary\steamapps\common\Fallout 4"
0.34 - Steam: Found game Deep Rock Galactic (548430) at "E:\SteamLibrary\steamapps\common\Deep Rock Galactic"
0.35 - Steam: Found game Disco Elysium (632470) at "E:\SteamLibrary\steamapps\common\Disco Elysium"
0.35 - Steam: Found game Counter-Strike: Global Offensive (730) at "E:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive"
0.35 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0.35 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.35 - GOG: GOG was not found in the registry
0.35 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.35 - Origin: Found no Ids and Paths in the MFST files
0.35 - Origin: Found no Ids for use with the Api
0.69 - Wabbajack Version: 2.5.3.22
0.82 - Build server is alive
0.82 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce
1.2 - Build server is alive
1.21 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce
2.22 - Loading ModLists from GitHub
16.29 - Starting to install Life in the Ruins
16.3 - Cleaning VFS, this may take a bit of time
16.31 - Starting Installer Task
16.31 - Installation has Started
16.31 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce
16.63 - Configuring Processor
16.63 - Install Folder: E:\Mods
16.63 - Downloads Folder: E:\Temp
16.63 - Game Folder: E:\SteamLibrary\steamapps\common\Fallout 4
16.63 - Wabbajack Folder: E:\Wabbajack\2.5.3.22
16.64 - Drive watcher is starting. Will warn at 8GB and error at 4GB
16.64 - Starting Drive watcher on E:\ currently 67.5GB free out of 930.6GB
16.64 - Validating Game ESMs
16.64 - Creating Output Folders
16.73 - Optimizing ModList
16.73 - Optimizing ModList directives
19.54 - Looking for files to delete
19.54 - Cleaning empty folders
19.82 - Looking for unmodified files
20 - Updating ModList
20 - Optimized 62817 directives to 62817 required
20.02 - Hashing Archives
20.02 - Looking for files to hash
20.07 - Found 679 total files, 626 matching filesize
32 - Downloading Missing Archives
32 - Missing 1 archives
32 - Getting Nexus API Key, if a browser appears, please accept
32.02 - Loading server whitelist
32.07 - Loaded permissions for 709 servers and 312 Google Drive files
32.07 - Getting upgrades list
32.08 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce
32.11 - Downloading Data_Fallout4.esm
34.83 - Hashed download is incorrect
34.83 - Loading for alternative to z0MibPYzG6g=
34.83 - No alternative for z0MibPYzG6g= could be found
34.88 - Hashing Remaining Archives
34.88 - Looking for files to hash
34.94 - Found 679 total files, 626 matching filesize
35.05 - Unable to download Data_Fallout4.esm (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4.esm)
35.05 - Cannot continue, was unable to download one or more archives
35.05 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce
35.07 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
35.16 - File hash check (-42) be8b5f281b8c8747bc6bd71f7f65020664fd9877b48ef5ab89b9d617fc5ca1ce

**Comment by marcelgcom** [comment]
Looks like my Data\Fallout4.esm file was actually corrupted and Steam fixed it then Wabbajack worked.
No issue here anymore. Thanks for the great work.
