### ISSUE TITLE
Timeout on modListSummary.json

### ISSUE THREAD

**Issue by pburkart** [wabbajack-tools/wabbajack#2073]
**Describe the bug**

When trying to browse the available modlists using Wabbajack, the modlists never load, and it just shows the loading icon spinning. It was working yesterday, and I was able to install a modpack for Skyrim SE with it. There have been no changes that I can think of that have been made since that time.

![image](https://i.imgur.com/H0AjBCx.png)

Viewing the log, it appears for some reason to be timing out trying to access the modlist json file found here: https://raw.githubusercontent.com/wabbajack-tools/mod-lists/master/reports/modListSummary.json

I can, however, access this file directly with my web browser no problem.

**Additional Context**

Windows 11 - Wabbajack Client 2.5.3.28
Installation Directory: `D:\Wabbajack`

**Attempted Solutions**

- Running as Administrator
- Clearing the in-app browser cache
- Enabling "Network Workaround (slow)" (unsure of what this does)
- Deleting the Wabbajack folder from locallow 
- Deleting the version folder (2.5.3.28) from the Wabbajack directory and reinstalling
- Adding an exception for Wabbajack in Windows Defender's Firewall

**Logs**

```
0.24 - Wabbajack Build - 61bf84638195bede893294b2c746492b7c13f553
0.24 - Running in D:\Wabbajack\2.5.3.28
0.27 - Detected Windows Version: 10.0.22000.0
0.27 - System settings - (15.8GB RAM) (3.7GB Page), Display: 1920 x 1080 (5.8GB VRAM - VideoMemorySizeMb=10240)
0.27 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.29 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.3 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0.3 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\SteamLibrary\steamapps\common\Skyrim Special Edition"
0.3 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.3 - GOG: GOG was not found in the registry
0.3 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.3 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.3 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.71 - Getting new Wabbajack version list
1.04 - Wabbajack Version: 2.5.3.28
1.24 - Build server is alive
1.24 - File hash check (-42) 93baf7ac9bdc593b1e283673cd7e67d926ba2dd32f700eef65b3cc2fb9fec312
1.28 - Build server is alive
1.28 - File hash check (-42) 93baf7ac9bdc593b1e283673cd7e67d926ba2dd32f700eef65b3cc2fb9fec312
2.62 - Loading ModLists from GitHub
102.66 - System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 94
102.66 - Http Connect error to https://raw.githubusercontent.com/wabbajack-tools/mod-lists/master/reports/modListSummary.json retry 1
130.83 - System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry, Nullable`1 token) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\Http\Client.cs:line 94
130.83 - Http Connect error to https://raw.githubusercontent.com/screaminglake/Whispering-Chills/main/modlists.json retry 1
```

**Comment by pburkart** [comment]
It looks almost like something happened with the executable. I redownloaded the application and it is working fine. Bizarre.
