### ISSUE TITLE
Browser Window displays does not display content, crashes Wabbajack on right click

### ISSUE THREAD

**Issue by choc137** [wabbajack-tools/wabbajack#2213]
**Describe the bug**

1. Launch Wabbajack.
2. Click the settings gear.
4. Click the "Login" button next to any of the services under "Logins".
5. The Browser Window pops up but does not seem to do much. Where the web frame ought to be, I see gray. I can copy the URL to the clipboard, move the window around, maximize it with either the maximize button or by dragging it to the top of the screen. I can't, however, drag the window using the title bar after it has been maximized. I have to un-maximize it using the corresponding button.
6. Right clicking anywhere but the min/max/close buttons on the Browser Window crashes Wabbajack.

![image](https://user-images.githubusercontent.com/98310755/202890870-c3b246ba-2193-4682-ba0a-90d7d19df821.png)

**Additional Context**

Windows 10
Version 21H2
Build 19044.2251

**Wabbajack Version**

3.0.4.1
8c60dc1197af3158fd844a3f0ae068766df2f0fc

**Logs**

```
00:00:00.422 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.422 [INFO] (Wabbajack.MainWindowVM) Process Location: C:\Modding\Wildlander\3.0.4.1\Wabbajack.exe
00:00:00.422 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.4.1
00:00:00.580 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 8c60dc1197af3158fd844a3f0ae068766df2f0fc
00:00:00.580 [INFO] (Wabbajack.MainWindow) Running in C:\Modding\Wildlander\3.0.4.1
00:00:00.613 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19044.0
...
00:00:00.613 [INFO] (Wabbajack.LauncherUpdater) Outside of standard install folder, not updating
...
00:00:04.393 [INFO] (Wabbajack.LoginManagers.NexusLoginManager) Logging into Nexus Mods
00:00:05.591 [ERROR] (Wabbajack.MainWindow) Uncaught error|System.InvalidOperationException: Can only call DragMove when primary mouse button is down.
   at System.Windows.Window.DragMove()
   at Wabbajack.BrowserWindow.UIElement_OnMouseDown(Object sender, MouseButtonEventArgs e) in C:\oss\wabbajack\Wabbajack.App.Wpf\Views\BrowserWindow.xaml.cs:line 26
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Wabbajack.App.Main()
```

**Comment by EzioTheDeadPoet** [comment]
Please install/repair WebView2 by using the installer from this link:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

repair means uninstall and do a fresh install.

**Comment by EzioTheDeadPoet** [comment]
solved by installing WebView2
