### ISSUE TITLE
Can't Download Any Modlist

### ISSUE THREAD

**Issue by Git-LocalCode** [wabbajack-tools/wabbajack#2247]
**Describe the bug**

Whenever I try to download a modlist, nothing happens.

**Additional Context**

Win 10. Skyrim Special Edition.

**Wabbajack Version**

v3.0.4.1

**Logs**

`````
############ Wabbajack log file - 2022-12-15 10:01:24.4432 ############
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1063730, Name = New World, Path = C:\Steam\steamapps\common\New World }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1843760, Name = Rogue Tower, Path = C:\Steam\steamapps\common\Rogue Tower }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 228980, Name = Steamworks Common Redistributables, Path = C:\Steam\steamapps\common\Steamworks Shared }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 244850, Name = Space Engineers, Path = C:\Steam\steamapps\common\SpaceEngineers }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 271590, Name = Grand Theft Auto V, Path = C:\Steam\steamapps\common\Grand Theft Auto V }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 445980, Name = Wizard of Legend, Path = C:\Steam\steamapps\common\Wizard of Legend }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, Path = C:\Steam\steamapps\common\Skyrim Special Edition }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 548430, Name = Deep Rock Galactic, Path = C:\Steam\steamapps\common\Deep Rock Galactic }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 846770, Name = DYSMANTLE, Path = C:\Steam\steamapps\common\DYSMANTLE }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 881100, Name = Noita, Path = C:\Steam\steamapps\common\Noita }
00:00:00.002 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 892970, Name = Valheim, Path = C:\Steam\steamapps\common\Valheim }
00:00:00.002 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Unable to open HKEY_LOCAL_MACHINE\Software\GOG.com\Games
00:00:00.002 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests does not exist!
00:00:00.002 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not contain any .mfst files
00:00:00.418 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.418 [INFO] (Wabbajack.MainWindowVM) Process Location: C:\Modded\3.0.4.1\Wabbajack.exe
00:00:00.418 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.4.1
00:00:00.588 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 8c60dc1197af3158fd844a3f0ae068766df2f0fc
00:00:00.588 [INFO] (Wabbajack.MainWindow) Running in C:\Modded\3.0.4.1
00:00:00.621 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19045.0
00:00:00.621 [INFO] (Wabbajack.MainWindow) System settings - (63,9GB RAM) (4GB Page), Display: 1920 x 1080 (10,8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.621 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:00.633 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:06.955 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Heartland
00:00:06.955 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Animonculory Visual Overhaul
00:00:06.993 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Xanza's Modded Skyrim
00:00:07.006 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Xanza's Modded Skyrim
00:00:07.083 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image FUS
00:00:07.096 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image FUS
00:00:07.137 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image The Phoenix Flavour - Dragon's Edition
00:00:07.144 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image The Phoenix Flavour - Dragon's Edition
00:00:07.294 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Capital Punishment
00:00:07.294 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Dungeons & Daedra
00:00:07.314 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Capital Punishment
00:00:07.380 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Dungeons & Daedra
00:00:07.543 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Tales from the Northern Lands
00:00:07.625 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Animonculory Dev Tools
00:00:07.640 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Wildlander
00:00:07.739 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image The Bustling Valley
00:00:08.318 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Legend of SkyrimVR
00:00:09.566 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Cyber Runner
00:00:19.025 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:00:20.417 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:00:21.349 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:00:22.203 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:01:19.302 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:01:20.006 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:01:20.526 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192
00:01:21.476 [ERROR] (Wabbajack.ModListGalleryVM) While downloading wj-featured|System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Networking.WabbajackClientApi.Client.SendMetric(String action, String subject) in C:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 82
   at Wabbajack.ModListMetadataVM.Download() in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListMetadataVM.cs:line 192

````

**Comment by EzioTheDeadPoet** [comment]
#2228 Most likely!

**Comment by Deilhade** [comment]
I have the same problem. Don't find Any answers (Discord,etc...)

"While downloading wj-featured|System.Net.Http.HttpRequestException : an error occured while sending a request"

Our IPS seems to be blocked. Even if I use my VPN.
What is it ? DNS ? API Key ?

If anybody have the answer, please...
