### ISSUE TITLE
wabbajack cant download game files

### ISSUE THREAD

**Issue by creative12as** [wabbajack-tools/wabbajack#2301]
**Describe the bug**

im downloading the mod list Horizon Roleplay Edition and when it gets to the end of the download it is unable to pull game files from the game folder so i copied them over to the download folder and it hashes them but still fails to download. ive verified my files and uninstalled reinstalled several times with no validation errors. the game is installed on my second ssd, no root folders.

**Additional Context**

windows 11 home fallout 4

**Wabbajack Version**
3.6.2 then tried to downgrade to 3.5.0 but i get the same problem

**Logs**
############ Wabbajack log file - 2023-02-27 19:41:11.8349 ############
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 228980, Name = Steamworks Common Redistributables, Path = C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared }
00:00:00.001 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 1172470, Name = Apex Legends, Path = D:\SteamLibrary\steamapps\common\Apex Legends }
00:00:00.001 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 22370, Name = Fallout 3 - Game of the Year Edition, Path = D:\SteamLibrary\steamapps\common\Fallout 3 goty }
00:00:00.001 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 22380, Name = Fallout: New Vegas, Path = D:\SteamLibrary\steamapps\common\Fallout New Vegas }
00:00:00.001 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 377160, Name = Fallout 4, Path = D:\SteamLibrary\steamapps\common\Fallout 4 }
00:00:00.001 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 990080, Name = Hogwarts Legacy, Path = D:\SteamLibrary\steamapps\common\Hogwarts Legacy }
00:00:00.001 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Unable to open HKEY_LOCAL_MACHINE\Software\GOG.com\Games
00:00:00.001 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests does not contain any .item files
00:00:00.001 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not exist!
00:00:00.347 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.347 [INFO] (Wabbajack.MainWindowVM) Process Location: C:\Users\nunya\OneDrive\Desktop\Wabbajack.exe
00:00:00.347 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.5.0
00:00:00.480 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 382feb1d8a0abe7adc50de6a14cfb072a04b9c68
00:00:00.480 [INFO] (Wabbajack.MainWindow) Running in C:\Users\nunya\OneDrive\Desktop
00:00:00.515 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.22621.0
00:00:00.515 [INFO] (Wabbajack.MainWindow) System settings - (15.9GB RAM) (2.9GB Page), Display: 2560 x 1440 (7.8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.515 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:00.515 [INFO] (Wabbajack.LauncherUpdater) Outside of standard install folder, not updating
00:00:52.892 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:52.892 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:52.892 [INFO] (Wabbajack.InstallerVM) Preparing GoogleDriveDownloader
00:00:52.892 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:52.910 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Horizon Roleplay Edition - 0.0.1.0
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: D:\HREinstall
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: D:\HREinstall\downloads
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: D:\SteamLibrary\steamapps\common\Fallout 4
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: C:\Users\nunya\OneDrive\Desktop
00:00:53.008 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:53.451 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:53.464 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:53.622 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:53.668 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:53.668 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 96019 directives to 96019 required
00:00:53.683 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:53.683 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:53.683 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:53.696 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:53.696 [INFO] (Wabbajack.Installer.StandardInstaller) Found 402 total files, 301 matching filesize
00:00:57.552 [WARN] (Wabbajack.InstallerVM) While loading slide|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Wabbajack.InstallerVM.PopulateNextModSlide(ModList modList)
00:01:01.732 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 8 archives
00:01:01.732 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:01:01.793 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:01:01.793 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:01:01.793 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 8 archives
00:01:01.793 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures9.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures9.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_DLCCoast - Textures.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_DLCCoast - Textures.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures6.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures6.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures5.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures5.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures4.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures4.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_DLCNukaWorld - Textures.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_DLCNukaWorld - Textures.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures2.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures2.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_Fallout4 - Textures1.ba2
00:01:01.797 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_Fallout4 - Textures1.ba2|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:01:01.797 [INFO] (Wabbajack.Installer.StandardInstaller) Found 402 total files, 301 matching filesize
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCCoast - Textures.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlccoast - textures.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures5.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures5.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures2.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures2.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures6.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures6.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures1.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures1.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures4.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures4.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCNukaWorld - Textures.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcnukaworld - textures.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Textures9.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - textures9.ba2)
00:01:01.826 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

[Wabbajack.00.log](https://github.com/wabbajack-tools/wabbajack/files/10846456/Wabbajack.00.log)

**Comment by EzioTheDeadPoet** [comment]
The list isn't supported anymore, and issues like that are depending on the files the lists requires based on it's hashes.
