### ISSUE TITLE
VPN Split Tunneling No Connection

### ISSUE THREAD

**Issue by RoseErrik-FS** [wabbajack-tools/wabbajack#2349]
**Describe the bug**

When using a VPN split tunneling to have Wabbajack not use the VPN but the regular connection there is no connection at all to the internet in anyway. When trying to launch it initially it gives an error of "Failed: An attempt was made to access a socket in a way forbidden by its access permissions. (api.github.com443). Then it just closes. If I disable the VPN and let it finish the install/download and then re-enable the VPN 

**Additional Context**

Windows 11 and No game
Wabbajack 3.1.0.0

Edit...
Figured I should add that the VPN service was Mullvad. Although I'm not to sure if that info is needed.

**Logs**

There is no log created. When trying to do the initial start of Wabbajack with the VPN and split tunneling enabled. But when yet again  disabling the VPN to let it run its course and then closing Wabbajack and then re-enabling the VPN it does create a log file.

```
############ Wabbajack log file - 2023-06-29 20:49:29.7187 ############
00:00:00.003 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1435828767, Name = The Elder Scrolls III: Morrowind GotY, Path = E:\Games - GoG\Morrowind }
00:00:00.320 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.320 [INFO] (Wabbajack.MainWindowVM) Process Location: E:\Modding\Wabbajack\3.1.0.0\Wabbajack.exe
00:00:00.320 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.1.0.0
00:00:00.443 [INFO] (Wabbajack.MainWindow) Wabbajack Build - cbc87f87499b87454453cc4726e5220f44af7e48
00:00:00.443 [INFO] (Wabbajack.MainWindow) Running in E:\Modding\Wabbajack\3.1.0.0
00:00:00.469 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.22621.0
00:00:00.469 [INFO] (Wabbajack.MainWindow) System settings - (79.9GB RAM) (14GB Page), Display: 2560 x 1440 (15.7GB VRAM - VideoMemorySizeMb=10240)
00:00:00.469 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:00.478 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:04.049 [ERROR] (Wabbajack.ModListGalleryVM) While loading lists|System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Wabbajack.Common.HttpExtensions.GetFromJsonAsync[TValue](HttpClient client, IResource`1 limiter, HttpRequestMessage msg, JsonSerializerOptions options, CancellationToken cancellationToken) in c:\oss\wabbajack\Wabbajack.Common\HttpExtensions.cs:line 53
   at Wabbajack.Networking.WabbajackClientApi.Client.LoadFeaturedLists() in c:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 226
   at Wabbajack.Networking.WabbajackClientApi.Client.LoadLists() in c:\oss\wabbajack\Wabbajack.Networking.WabbajackClientApi\Client.cs:line 198
   at Wabbajack.ModListGalleryVM.LoadModLists() in c:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Gallery\ModListGalleryVM.cs:line 235
```

**Comment by EzioTheDeadPoet** [comment]
that's something that mullvad would need to fix with their split tunneling then.

**Comment by EzioTheDeadPoet** [comment]
Or did you not apply the split to all relevant Wabbajack.exe files ?

Since Wabbajack has one main launcher and then the main program that's inside the version folders.

**Comment by RoseErrik-FS** [comment]
I just double checked I have both Wabbajack.exe files whitelisted in the client... So its not that. I will also send them an email. Just to cover both sides.
