### ISSUE TITLE
Nexus Mod Download Failures

### ISSUE THREAD

**Issue by jfurtado-cfc** [wabbajack-tools/wabbajack#2433]
**Describe the bug**
Nexus Mod file download is not working. I last downloaded the Fahdon modlist on 10/19 using Wabbajack v3.2.0.1, with minimal issues. 

I resumed downloading the modlist yesterday 10/27. The Wabbajack version automatically upgraded to v3.3.0.0, and I've had nothing but issues since. 

The first issue that I had was getting the connection to Nexus reestablished; this may have to do with Nexus, as the bot detector and third party authentication was not being activated.

After getting connected to Nexus, the file downloads started, with ~500 mods left to download. When I ended the downloads yesterday, I had ~40 left to download. This morning, I found that 470 mods still need downloaded. When I looked at the Downloads folder, only 43 files were added yesterday. None of the other files downloaded.

Based on the below log file, the new mod files have blank file names.

**Additional Context**
Win 11, SSE, Fahdon

**Wabbajack Version**
v3.3.0.0

**Logs**

[Wabbajack.19.log](https://github.com/wabbajack-tools/wabbajack/files/13196298/Wabbajack.19.log)

**Comment by jfurtado-cfc** [comment]
After rereading the log error, there appears to be an issue parsing out the mod file format.

00:02:28.178 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Deadly Spell Impacts - Mysticism-71724-1-0-1658281894.7z|System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at Wabbajack.Common.HttpExtensions.AddCookies(HttpRequestMessage msg, Cookie[] cookies) in C:\oss\wabbajack\Wabbajack.Common\HttpExtensions.cs:line 21
   at Wabbajack.Common.HttpExtensions.ToHttpRequestMessage(BrowserDownloadState browserState) in C:\oss\wabbajack\Wabbajack.Common\HttpExtensions.cs:line 44
   at Wabbajack.Downloaders.NexusDownloader.DownloadManually(Archive archive, Nexus state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Nexus\NexusDownloader.cs:line 191
   at Wabbajack.Downloaders.NexusDownloader.Download(Archive archive, Nexus state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Nexus\NexusDownloader.cs:line 123
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 112
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 54
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 155
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 399

**Comment by EzioTheDeadPoet** [comment]
use this https://github.com/wabbajack-tools/wabbajack/releases/tag/3.3.0.0-pre
