### ISSUE TITLE
Wabbajack 3.4.0.0 crashes immediately with .NET runtime error

### ISSUE THREAD

**Issue by uspiz** [wabbajack-tools/wabbajack#2466]
Every wabbajack version from 3.0 onwards crashes immediately with the splash screen on screen for few seconds. The 2.5.3.28 I downloaded from github launches just fine.

I've updated all the .NET runtime and SDK files. I'm on Windows 10 latest version 22H2. Wabbajack works on my newer win11 pc just fine.

Application: Wabbajack.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x87AF03F3): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Wabbajack.VFS.FileHashCache..ctor(AbsolutePath location, IResource`1 limiter) in c:\oss\wabbajack\Wabbajack.VFS\FileHashCache.cs:line 30
   at Wabbajack.Services.OSIntegrated.ServiceExtensions.<>c__DisplayClass0_0.<AddOSIntegrated>b__3(IServiceProvider s) in c:\oss\wabbajack\Wabbajack.Services.OSIntegrated\ServiceExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Wabbajack.Downloaders.ServiceExtensions.<>c__DisplayClass0_0.<AddDownloadDispatcher>b__0(IServiceProvider s) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\ServiceExtensions.cs:line 55
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Wabbajack.App.<>c__DisplayClass1_0.<OnStartup>b__1(IScheduler _, Int32 _) in c:\oss\wabbajack\Wabbajack.App.Wpf\App.xaml.cs:line 85
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Wpf/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Wabbajack.App.Main()

---------------------------------------------------------------------------------------------------------------------------------------------------

############ Wabbajack log file - 2023-12-19 00:03:03.6882 ############
00:00:00.000 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 228980, Name = Steamworks Common Redistributables, InstallationDirectoryName = Steamworks Shared }, LibraryFolder = C:/Program Files (x86)/Steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 228980, Name = Steamworks Common Redistributables, Path = C:/Program Files (x86)/Steam/steamapps/common/Steamworks Shared }
00:00:00.002 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1213210, Name = Command & Conquer™ Remastered Collection, InstallationDirectoryName = CnCRemastered }, LibraryFolder = D:/SteamLibrary, SteamPath = C:/Program Files (x86)/Steam, AppId = 1213210, Name = Command & Conquer™ Remastered Collection, Path = D:/SteamLibrary/steamapps/common/CnCRemastered }
00:00:00.002 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 253710, Name = theHunter Classic, InstallationDirectoryName = theHunter }, LibraryFolder = D:/SteamLibrary, SteamPath = C:/Program Files (x86)/Steam, AppId = 253710, Name = theHunter Classic, Path = D:/SteamLibrary/steamapps/common/theHunter }
00:00:00.002 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 837590, Name = Operation Thunderstorm, InstallationDirectoryName = Operation Thunderstorm }, LibraryFolder = D:/SteamLibrary, SteamPath = C:/Program Files (x86)/Steam, AppId = 837590, Name = Operation Thunderstorm, Path = D:/SteamLibrary/steamapps/common/Operation Thunderstorm }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1076977034, Name = Northgard, Path = D:/Pelit/Northgard }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1207658995, Name = Deus Ex GOTY, Path = E:/Pelit/Deus Ex GOTY }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1426071866, Name = DOOM II Enhanced, Path = D:/Pelit/DOOM II Enhanced }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1454315831, Name = Fallout 3, Path = d:/pelit/fallout 3 }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1454587428, Name = Fallout: New Vegas, Path = D:/Pelit/Fallout New Vegas }
00:00:00.017 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found GOGGame { Id = 1525634891, Name = Deus Ex Revision, Path = E:/Pelit/Deus Ex GOTY }
00:00:00.030 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found EGSGame { CatalogItemId = 84e94f1900874df4a9281e6b5793653e, DisplayName = BioShock 2 Remastered, InstallLocation = D:/Pelit/BioShock2Remastered }
00:00:00.030 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found EGSGame { CatalogItemId = c7934d31d2ed473cb4b000c24e049927, DisplayName = BioShock Remastered, InstallLocation = D:/Pelit/BioshockRemastered }
00:00:00.030 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found EGSGame { CatalogItemId = 886507fcf6b94d98a02a018418fffd1f, DisplayName = DOOM 64, InstallLocation = E:/Pelit/DOOM64 }
00:00:00.030 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found EGSGame { CatalogItemId = 19e3c0be6d6c4d4b84b1bc2248f94b43, DisplayName = Quake, InstallLocation = D:/Pelit/Quake }
00:00:00.030 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:/ProgramData/Origin/LocalContent does not exist!

**Comment by uspiz** [comment]
Managed to solve it by myself. For some reason I had to give full user rights for all user groups in the Appdata/wabbajack folder.
