### ISSUE TITLE
Version 3.5.0.1 crashes with file, 3.0.5.0 runs fine

### ISSUE THREAD

**Issue by cbbravo** [wabbajack-tools/wabbajack#2501]
**Describe the bug**

1. Download the wabbajack file here: https://www.nexusmods.com/fallout4/mods/71281?tab=files
2. Launch wabbajack, cilck "Install from disk"
3. For "target Modlist" select the extracted .wabbajack file
4. Select any folders for "Modlist installation location" and "Resource Download Location"
5. Click start
6. Wabbajack now crashes without any message

**Additional Context**

OS: Win10
Game: Fallout 4 VR

**Wabbajack Version**

3.5.0.1 crashes
3.0.5.0 runs fine
I haven't tested the versions in between

**Logs**

```############ Wabbajack log file - 2024-02-02 21:13:40.6044 ############
00:00:00.000 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 228980, Name = Steamworks Common Redistributables, InstallationDirectory = C:/Program Files (x86)/Steam/steamapps/common/Steamworks Shared }, LibraryFolder = C:/Program Files (x86)/Steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 228980, Name = Steamworks Common Redistributables, Path = C:/Program Files (x86)/Steam/steamapps/common/Steamworks Shared }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 250820, Name = SteamVR, InstallationDirectory = C:/Program Files (x86)/Steam/steamapps/common/SteamVR }, LibraryFolder = C:/Program Files (x86)/Steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 250820, Name = SteamVR, Path = C:/Program Files (x86)/Steam/steamapps/common/SteamVR }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 719950, Name = Windows Mixed Reality for SteamVR , InstallationDirectory = C:/Program Files (x86)/Steam/steamapps/common/MixedRealityVRDriver }, LibraryFolder = C:/Program Files (x86)/Steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 719950, Name = Windows Mixed Reality for SteamVR , Path = C:/Program Files (x86)/Steam/steamapps/common/MixedRealityVRDriver }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 107410, Name = Arma 3, InstallationDirectory = G:/_steam/steamapps/common/Arma 3 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 107410, Name = Arma 3, Path = G:/_steam/steamapps/common/Arma 3 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1096530, Name = Solasta: Crown of the Magister, InstallationDirectory = G:/_steam/steamapps/common/Slasta_COTM }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1096530, Name = Solasta: Crown of the Magister, Path = G:/_steam/steamapps/common/Slasta_COTM }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1151340, Name = Fallout 76, InstallationDirectory = G:/_steam/steamapps/common/Fallout76 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1151340, Name = Fallout 76, Path = G:/_steam/steamapps/common/Fallout76 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1259420, Name = Days Gone, InstallationDirectory = G:/_steam/steamapps/common/Days Gone }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1259420, Name = Days Gone, Path = G:/_steam/steamapps/common/Days Gone }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1268750, Name = Starship Troopers: Extermination, InstallationDirectory = G:/_steam/steamapps/common/StarshipTroopersExtermination }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1268750, Name = Starship Troopers: Extermination, Path = G:/_steam/steamapps/common/StarshipTroopersExtermination }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1874880, Name = Arma Reforger, InstallationDirectory = G:/_steam/steamapps/common/Arma Reforger }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1874880, Name = Arma Reforger, Path = G:/_steam/steamapps/common/Arma Reforger }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1874910, Name = Arma Reforger Tools, InstallationDirectory = G:/_steam/steamapps/common/Arma Reforger Tools }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1874910, Name = Arma Reforger Tools, Path = G:/_steam/steamapps/common/Arma Reforger Tools }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 221100, Name = DayZ, InstallationDirectory = G:/_steam/steamapps/common/DayZ }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 221100, Name = DayZ, Path = G:/_steam/steamapps/common/DayZ }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 223100, Name = Homefront: The Revolution, InstallationDirectory = G:/_steam/steamapps/common/Homefront_The_Revolution }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 223100, Name = Homefront: The Revolution, Path = G:/_steam/steamapps/common/Homefront_The_Revolution }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 230410, Name = Warframe, InstallationDirectory = G:/_steam/steamapps/common/Warframe }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 230410, Name = Warframe, Path = G:/_steam/steamapps/common/Warframe }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 271590, Name = Grand Theft Auto V, InstallationDirectory = G:/_steam/steamapps/common/Grand Theft Auto V }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 271590, Name = Grand Theft Auto V, Path = G:/_steam/steamapps/common/Grand Theft Auto V }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 275850, Name = No Man's Sky, InstallationDirectory = G:/_steam/steamapps/common/No Man's Sky }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 275850, Name = No Man's Sky, Path = G:/_steam/steamapps/common/No Man's Sky }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 292030, Name = The Witcher 3: Wild Hunt, InstallationDirectory = G:/_steam/steamapps/common/The Witcher 3 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 292030, Name = The Witcher 3: Wild Hunt, Path = G:/_steam/steamapps/common/The Witcher 3 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 342180, Name = Arizona Sunshine, InstallationDirectory = G:/_steam/steamapps/common/ArizonaSunshine }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 342180, Name = Arizona Sunshine, Path = G:/_steam/steamapps/common/ArizonaSunshine }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 359320, Name = Elite Dangerous, InstallationDirectory = G:/_steam/steamapps/common/Elite Dangerous }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 359320, Name = Elite Dangerous, Path = G:/_steam/steamapps/common/Elite Dangerous }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 377160, Name = Fallout 4, InstallationDirectory = G:/_steam/steamapps/common/Fallout 4 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 377160, Name = Fallout 4, Path = G:/_steam/steamapps/common/Fallout 4 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 397540, Name = Borderlands 3, InstallationDirectory = G:/_steam/steamapps/common/Borderlands 3 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 397540, Name = Borderlands 3, Path = G:/_steam/steamapps/common/Borderlands 3 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 460930, Name = Tom Clancy's Ghost Recon® Wildlands, InstallationDirectory = G:/_steam/steamapps/common/Wildlands }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 460930, Name = Tom Clancy's Ghost Recon® Wildlands, Path = G:/_steam/steamapps/common/Wildlands }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 480490, Name = Prey, InstallationDirectory = G:/_steam/steamapps/common/Prey }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 480490, Name = Prey, Path = G:/_steam/steamapps/common/Prey }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, InstallationDirectory = G:/_steam/steamapps/common/Skyrim Special Edition }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, Path = G:/_steam/steamapps/common/Skyrim Special Edition }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 513710, Name = SCUM, InstallationDirectory = G:/_steam/steamapps/common/SCUM }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 513710, Name = SCUM, Path = G:/_steam/steamapps/common/SCUM }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 518790, Name = theHunter: Call of the Wild™, InstallationDirectory = G:/_steam/steamapps/common/theHunterCotW }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 518790, Name = theHunter: Call of the Wild™, Path = G:/_steam/steamapps/common/theHunterCotW }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 534380, Name = Dying Light 2, InstallationDirectory = G:/_steam/steamapps/common/Dying Light 2 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 534380, Name = Dying Light 2, Path = G:/_steam/steamapps/common/Dying Light 2 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 548430, Name = Deep Rock Galactic, InstallationDirectory = G:/_steam/steamapps/common/Deep Rock Galactic }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 548430, Name = Deep Rock Galactic, Path = G:/_steam/steamapps/common/Deep Rock Galactic }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 552520, Name = Far Cry 5, InstallationDirectory = G:/_steam/steamapps/common/FarCry5 }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 552520, Name = Far Cry 5, Path = G:/_steam/steamapps/common/FarCry5 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 611660, Name = Fallout 4 VR, InstallationDirectory = G:/_steam/steamapps/common/Fallout 4 VR }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 611660, Name = Fallout 4 VR, Path = G:/_steam/steamapps/common/Fallout 4 VR }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 704270, Name = Generation Zero®, InstallationDirectory = G:/_steam/steamapps/common/GenerationZero }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 704270, Name = Generation Zero®, Path = G:/_steam/steamapps/common/GenerationZero }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 895400, Name = Deadside, InstallationDirectory = G:/_steam/steamapps/common/Deadside }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 895400, Name = Deadside, Path = G:/_steam/steamapps/common/Deadside }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 914620, Name = Mist Survival, InstallationDirectory = G:/_steam/steamapps/common/Mist Survival }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 914620, Name = Mist Survival, Path = G:/_steam/steamapps/common/Mist Survival }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 976730, Name = Halo: The Master Chief Collection, InstallationDirectory = G:/_steam/steamapps/common/Halo The Master Chief Collection }, LibraryFolder = G:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 976730, Name = Halo: The Master Chief Collection, Path = G:/_steam/steamapps/common/Halo The Master Chief Collection }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1085660, Name = Destiny 2, InstallationDirectory = J:/_steam/steamapps/common/Destiny 2 }, LibraryFolder = J:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1085660, Name = Destiny 2, Path = J:/_steam/steamapps/common/Destiny 2 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1086940, Name = Baldur's Gate 3, InstallationDirectory = J:/_steam/steamapps/common/Baldurs Gate 3 }, LibraryFolder = J:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1086940, Name = Baldur's Gate 3, Path = J:/_steam/steamapps/common/Baldurs Gate 3 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1091500, Name = Cyberpunk 2077, InstallationDirectory = J:/_steam/steamapps/common/Cyberpunk 2077 }, LibraryFolder = J:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1091500, Name = Cyberpunk 2077, Path = J:/_steam/steamapps/common/Cyberpunk 2077 }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 1361210, Name = Warhammer 40,000: Darktide, InstallationDirectory = J:/_steam/steamapps/common/Warhammer 40,000 DARKTIDE }, LibraryFolder = J:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 1361210, Name = Warhammer 40,000: Darktide, Path = J:/_steam/steamapps/common/Warhammer 40,000 DARKTIDE }
00:00:00.019 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppManifest = { AppId = 379430, Name = Kingdom Come: Deliverance, InstallationDirectory = J:/_steam/steamapps/common/KingdomComeDeliverance }, LibraryFolder = J:/_steam, SteamPath = C:/Program Files (x86)/Steam, AppId = 379430, Name = Kingdom Come: Deliverance, Path = J:/_steam/steamapps/common/KingdomComeDeliverance }
00:00:00.019 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1448452156, Name = Dying Light: The Following – Enhanced Edition, Path = D:/GOG Games/Dying Light }
00:00:00.019 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1460996021, Name = Dying Light: Gun Psycho Bundle, Path = D:/GOG Games/Dying Light }
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1460996196, Name = Dying Light: Harran Ranger Bundle, Path = D:/GOG Games/Dying Light }
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1460996282, Name = Dying Light: Volatile Hunter Bundle, Path = D:/GOG Games/Dying Light }
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1539474600, Name = Dying Light: White Death Bundle, Path = D:/GOG Games/Dying Light }
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1841289280, Name = Dying Light: Vintage Gunslinger Bundle, Path = D:/GOG Games/Dying Light }
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) The manifest directory C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests does not contain any .item files
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:/ProgramData/Origin/LocalContent does not exist!
00:00:00.032 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Data folder C:/ProgramData/EA Desktop does not exist!
00:00:00.485 [INFO] (Wabbajack.MainWindowVM) Assembly Location: G:\Wabbajack\3.5.0.1\Wabbajack.dll
00:00:00.485 [INFO] (Wabbajack.MainWindowVM) Process Location: G:\Wabbajack\3.5.0.1\Wabbajack.exe
00:00:00.485 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.5.0.1
00:00:00.485 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: d9190e505fe6a16f0f4b668560497c61b9c194d81d101f4366a184b70e065123
00:00:00.485 [INFO] (Wabbajack.Networking.WabbajackClientApi.Client) Init Client: d9190e505fe6a16f0f4b668560497c61b9c194d81d101f4366a184b70e065123
00:00:00.686 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 5facc21865ebdd55e6be504e359a2dc1a66a6705
00:00:00.686 [INFO] (Wabbajack.MainWindow) Running in G:\Wabbajack\3.5.0.1
00:00:00.692 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19045.0
00:00:00.692 [INFO] (Wabbajack.MainWindow) System settings - (15.9GB RAM) (11.5GB Page), Display: 1920 x 1080 (5.8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.692 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:00.722 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:03.270 [ERROR] (Wabbajack.InstallerVM) While loading modlist|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.InstallerVM.PopulateSlideShow(ModList modList) in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 568
   at Wabbajack.InstallerVM.LoadModlist(AbsolutePath path, ModlistMetadata metadata) in C:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 439
00:00:04.782 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:04.783 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:04.834 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Fallout 4 VR - Modern Tactical Overhaul - 0.0.1.0
00:00:04.849 [ERROR] (Wabbajack.Networking.WabbajackClientApi.Client) HTTP Error: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Fri, 02 Feb 2024 20:13:45 GMT
  Connection: keep-alive
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=PMfqHQp5x%2FBi4yWrdhWtOc9xq26WzNpvjKW1%2BTCMXSGn7qsoDbUosZ32MeeA%2B28DouWC9J6LFWtzurx43Jd3x5dGboDrtQhVQtJZKVYe5jirGcqgtQbl11b%2Bu0NUYVjPidBjKv7Sy510K6tVSL0HMI0%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 84f518b78b286d79-MUC
  Content-Type: text/plain
  Content-Length: 54
}
```

**Comment by tr4wzified** [comment]
I don't remember all the changes since 3.0.5.0, but modlists compiled with versions before 3.5 need to be recompiled. Wabbajack had a pretty critical file corruption issue with BSAs that was solved in this version, that occurred while compiling the modlist so to say. The new version can't install those broken lists, it's not backwards compatible.
