### ISSUE TITLE
Compilation [ERROR] "Key already added" causing UI issues

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [wabbajack-tools/wabbajack#2503]
**Describe the bug**

Compilation screen gets set to failed state while WJ continues on with the compile due to an "harmless/expected" error that isn't caught properly. This error might also be the reason why WJ doesn't properly delete temporary data during compilation resulting in the high storage requirement.

**Wabbajack Version**

3.5.0.1

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/14164273/Wabbajack.current.log)

```log
00:01:42.700 [ERROR] (Wabbajack.VFS.Context) Error while examining the contents of Bighorner - Textures.BA2|System.ArgumentException: An item with the same key has already been added. Key: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtractWithBSA[T](IStreamFactory sFn, FileType sig, Predicate`1 shouldExtract, Func`3 mapFn, CancellationToken token) in C:\oss\wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 254
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtract[T](IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, CancellationToken token, HashSet`1 onlyFiles, Action`1 progressFunction) in C:\oss\wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 117
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtract[T](IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, CancellationToken token, HashSet`1 onlyFiles, Action`1 progressFunction) in C:\oss\wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 133
   at Wabbajack.VFS.VirtualFile.Analyze(Context context, VirtualFile parent, IStreamFactory extractedFile, IPath relPath, CancellationToken token, Int32 depth, IJob job) in C:\oss\wabbajack\Wabbajack.VFS\VirtualFile.cs:line 233
```

**Comment by Hotiraripha** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/14165773/Wabbajack.current.log)
