### ISSUE TITLE
Error when keeping files from a previous autoinstallation?

### ISSUE THREAD

**Issue by giraldiego** [wabbajack-tools/wabbajack#26]
**Describe the bug**

I got this error when trying to compile a new modlist for Lexy's:

239.42 -    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Wabbajack.Compiler.BuildPatches()
   at Wabbajack.Compiler.Compile()
   at Wabbajack.AppState.<>c__DisplayClass75_1.<ExecuteBegin>b__3()
239.42 - System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Wabbajack.Compiler.BuildPatches()
   at Wabbajack.Compiler.Compile()
   at Wabbajack.AppState.<>c__DisplayClass75_1.<ExecuteBegin>b__3()
239.43 - An item with the same key has already been added. - Can't continue

**Additional context**

I think the bug is because the autoinstaller generates some folders inside the MO2 folder like the "LOOT Config Files" with some files the user has to manually relocate for their installation.  If one tries to build a new modlist using the same MO2 folder and let this files, it will get the error.

I solved the error, deleting that folder. Probably it would happen if the user keeps the folder "Game Folder Files".

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by erri120** [comment]
Should be fixed by now
