### ISSUE TITLE
Not logged in during compilation isnt failing when verifying mods.

### ISSUE THREAD

**Issue by Mieekaserra** [wabbajack-tools/wabbajack#2622]
**Describe the bug**

If a user isnt logged in when running thought compilation you get warnings that it cannot verify new mods in your download folder. This Inevitably leads to a "no match in stack"  error.

**Wabbajack Version**

3.7.2

**Logs**

```
00:00:22.986 [WARN] (Wabbajack.Compiler.MO2Compiler) While resolving archive 2K Tints - Men - NITHI NPCs - The Thieves Guild-79762-1-0-0-1671549762.7z|System.Exception: No API Key or OAuth Token found for NexusMods
   at Wabbajack.Networking.NexusApi.NexusApi.AddAuthHeaders(HttpRequestMessage msg) in E:\oss\wabbajack\Wabbajack.Networking.NexusApi\NexusApi.cs:line 221
   at Wabbajack.Networking.NexusApi.NexusApi.GenerateMessage(HttpMethod method, String uri, Object[] parameters) in E:\oss\wabbajack\Wabbajack.Networking.NexusApi\NexusApi.cs:line 197
   at Wabbajack.Networking.NexusApi.ProxiedNexusApi.GenerateMessage(HttpMethod method, String uri, Object[] parameters) in E:\oss\wabbajack\Wabbajack.Networking.NexusApi\ProxiedNexusApi.cs:line 41
   at Wabbajack.Networking.NexusApi.NexusApi.FileInfo(String nexusGameName, Int64 modId, Int64 fileId, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Networking.NexusApi\NexusApi.cs:line 107
   at Wabbajack.Downloaders.NexusDownloader.Verify(Archive archive, Nexus state, IJob job, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Downloaders.Nexus\NexusDownloader.cs:line 206
   at Wabbajack.Downloaders.DownloadDispatcher.Verify(Archive a, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 146
   at Wabbajack.Compiler.ACompiler.ResolveArchive(IndexedArchive archive) in E:\oss\wabbajack\Wabbajack.Compiler\ACompiler.cs:line 647
```

**Comment by EzioTheDeadPoet** [comment]
The request for improvement is that WJ throws an error that stops the compilation the moment the OAuth error is detected.
