### ISSUE TITLE
CDN Download for Enbseries Causes Null Reference Exception

### ISSUE THREAD

**Issue by sammyshear** [wabbajack-tools/wabbajack#2623]
**Describe the bug**

When trying to install the modlist Zenithar's Forge, all downloads work except for the enbseries download from the wabbajack CDN, which throws a Null Reference Exception per the logs.

**Additional Context**

OS: Win 10
Game Type: SSE

**Wabbajack Version**

3.7.3.0

**Logs**

```
00:00:04.325 [ERROR] Download error for file enbseries_skyrimse_v0499.zip|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 124
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in E:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 116
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in E:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 57
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in E:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 162
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in E:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 413
```

**Comment by EzioTheDeadPoet** [comment]
The list needs to be updated.
