### ISSUE TITLE
Wabbajack.InstallerVM The parameter is incorrect

### ISSUE THREAD

**Issue by fzzinchemical** [wabbajack-tools/wabbajack#2639]
**Describe the bug**

During the extraction process a System.IO.IOException is caught when reaching the end of the process. Tried out multiple modlists with the same results. Almost the entire modlist is processed, the issue always appears at the end. 

**Additional Context**

Windows 10 22H2 running under Virtualbox, also tested native with same results.
Downloads Drive is formated in Ext4
Installation Drive is formated in NTFS

**Wabbajack Version**
3.7.0.0 and 3.7.3.0

**Logs**

```cmd
03:11:41.079 [ERROR] (Wabbajack.InstallerVM) The parameter is incorrect. : 'F:\Skyrim_Mods\Modlist\__temp__\f9570124-bedf-4bd0-bd51-b6a91b197d7a\meshes\Kreis\KSA\azureskyfarer\ksa_azureskyfarer_handsF-H_0.nif'|System.IO.IOException: The parameter is incorrect. : 'F:\Skyrim_Mods\Modlist\__temp__\f9570124-bedf-4bd0-bd51-b6a91b197d7a\meshes\Kreis\KSA\azureskyfarer\ksa_azureskyfarer_handsF-H_0.nif'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at Wabbajack.Common.NativeFileStreamFactory.GetStream() in c:\oss\Wabbajack\Wabbajack.Common\NativeFileStreamFactory.cs:line 30
   at Wabbajack.Installer.AInstaller`1.<>c__DisplayClass65_0.<<InstallArchives>b__5>d.MoveNext() in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 279
--- End of stack trace from previous location ---
   at Wabbajack.VFS.Context.<>c__DisplayClass21_0.<<Extract>g__HandleFile|3>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 125
--- End of stack trace from previous location ---
   at Wabbajack.VFS.Context.<>c__DisplayClass21_1.<<Extract>b__7>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 135
--- End of stack trace from previous location ---
   at Wabbajack.FileExtractor.FileExtractor.<>c__DisplayClass16_0`1.<<GatheringExtractWith7Zip>b__4>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 376
--- End of stack trace from previous location ---
   at Wabbajack.Common.AsyncParallelExtensions.SelectAsync[TIn,TOut](IEnumerable`1 coll, Func`2 fn)+MoveNext() in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 283
   at Wabbajack.Common.AsyncParallelExtensions.SelectAsync[TIn,TOut](IEnumerable`1 coll, Func`2 fn)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Wabbajack.Common.AsyncParallelExtensions.Where[T](IAsyncEnumerable`1 coll, Predicate`1 p)+MoveNext() in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 274
   at Wabbajack.Common.AsyncParallelExtensions.Where[T](IAsyncEnumerable`1 coll, Predicate`1 p)+MoveNext() in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 274
   at Wabbajack.Common.AsyncParallelExtensions.Where[T](IAsyncEnumerable`1 coll, Predicate`1 p)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Wabbajack.Common.AsyncParallelExtensions.ToDictionary[T,TK,TV](IAsyncEnumerable`1 coll, Func`2 kSelector, Func`2 vSelector) in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 268
   at Wabbajack.Common.AsyncParallelExtensions.ToDictionary[T,TK,TV](IAsyncEnumerable`1 coll, Func`2 kSelector, Func`2 vSelector) in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 268
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtractWith7Zip[T](IStreamFactory sf, Predicate`1 shouldExtract, Func`3 mapfn, IReadOnlyCollection`1 onlyFiles, CancellationToken token, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 370
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtractWith7Zip[T](IStreamFactory sf, Predicate`1 shouldExtract, Func`3 mapfn, IReadOnlyCollection`1 onlyFiles, CancellationToken token, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 392
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtractWith7Zip[T](IStreamFactory sf, Predicate`1 shouldExtract, Func`3 mapfn, IReadOnlyCollection`1 onlyFiles, CancellationToken token, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 392
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtract[T](IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, CancellationToken token, HashSet`1 onlyFiles, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 105
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtract[T](IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, CancellationToken token, HashSet`1 onlyFiles, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 105
   at Wabbajack.FileExtractor.FileExtractor.GatheringExtract[T](IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, CancellationToken token, HashSet`1 onlyFiles, Action`1 progressFunction) in c:\oss\Wabbajack\Wabbajack.FileExtractor\FileExtractor.cs:line 133
   at Wabbajack.VFS.Context.<>c__DisplayClass21_0.<<Extract>g__HandleFile|3>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 131
--- End of stack trace from previous location ---
   at Wabbajack.VFS.Context.<>c__DisplayClass21_0.<<Extract>g__HandleFile|3>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 149
--- End of stack trace from previous location ---
   at Wabbajack.VFS.Context.<>c__DisplayClass21_0.<<Extract>g__HandleFile|3>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 149
--- End of stack trace from previous location ---
   at Wabbajack.VFS.Context.<>c__DisplayClass21_0.<<Extract>b__4>d.MoveNext() in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 157
--- End of stack trace from previous location ---
   at Wabbajack.Common.AsyncParallelExtensions.PDoAll[TIn](IEnumerable`1 coll, Func`2 mapFn) in c:\oss\Wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 15
   at Wabbajack.VFS.Context.Extract(HashSet`1 files, Func`3 callback, CancellationToken token, Nullable`1 tempFolder, Boolean runInParallel) in c:\oss\Wabbajack\Wabbajack.VFS\Context.cs:line 156
   at Wabbajack.Installer.AInstaller`1.InstallArchives(CancellationToken token) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 233
   at Wabbajack.Installer.StandardInstaller.Begin(CancellationToken token) in c:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 140
   at Wabbajack.InstallerVM.<BeginInstall>b__134_0() in c:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 527
```

**Edit:**

It might be due to the download folder formatted in Ext4.

**Comment by tr4wzified** [comment]
Just wondering how you tested this? Windows does not have ext4 support as far as I know, do you use extra software for this?

**Comment by tr4wzified** [comment]
Also, can you attach the full log so we have more context?

**Comment by fzzinchemical** [comment]
This has been a me issue, sorry about that. I was using the [Omni-Guide](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/wiki/Wabbajack-on-Linux-via-Wine) to run Wabbajack under linux with wine. 

Using Bottles fixed it in my case, so no modifications necessary.

Thank you @tr4wzified  for your time and support, I'll close the issue.
