### ISSUE TITLE
Wabbajack fails when downloads directory is on a mapped network drive

### ISSUE THREAD

**Issue by LP0101** [wabbajack-tools/wabbajack#295]
**Describe the bug**
When pointing the downloads directory to a network drive, Wabbajack fails to benchmark it.

In this case, I'm pointing my downloads to `S:\MO2 VR Downloads`

**Additional context**
Windows 10, Skyrim VR

**Logs**
```
0 - Extracting libCef files
0.14 - The contents of cefglue.7z are being extracted to . using 7zip.exe
2.06 - Wabbajack Build - 02109a05bddfa571a6b2eef796d57aed44886616
31.21 - Benchmarking C:\Skyrim VR MO2
33.59 - 749.9MB/sec for C:\Skyrim VR MO2
33.59 - Benchmarking S:\MO2 VR Downloads
33.62 -    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Wabbajack.Common.Utils.<TestDiskSpeed>d__76.MoveNext() in d:\work\1\s\Wabbajack.Common\Utils.cs:line 842
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<RecommendQueueSize>d__42.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.AInstaller.<RecommendQueueSize>d__41.MoveNext() in d:\work\1\s\Wabbajack.Lib\AInstaller.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.MO2Installer.<_Begin>d__11.MoveNext() in d:\work\1\s\Wabbajack.Lib\MO2Installer.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<<Begin>b__44_0>d.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass27_1.<<-ctor>b__18>d.MoveNext()
33.62 - System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Wabbajack.Common.Utils.<TestDiskSpeed>d__76.MoveNext() in d:\work\1\s\Wabbajack.Common\Utils.cs:line 842
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<RecommendQueueSize>d__42.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.AInstaller.<RecommendQueueSize>d__41.MoveNext() in d:\work\1\s\Wabbajack.Lib\AInstaller.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.MO2Installer.<_Begin>d__11.MoveNext() in d:\work\1\s\Wabbajack.Lib\MO2Installer.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<<Begin>b__44_0>d.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass27_1.<<-ctor>b__18>d.MoveNext()
33.63 - Value cannot be null.
Parameter name: key - Can't continue
82.9 - Benchmarking C:\Skyrim VR MO2
82.91 - 749.9MB/sec for C:\Skyrim VR MO2
82.92 - Benchmarking S:\MO2 VR Downloads
82.93 -    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Wabbajack.Common.Utils.<TestDiskSpeed>d__76.MoveNext() in d:\work\1\s\Wabbajack.Common\Utils.cs:line 842
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<RecommendQueueSize>d__42.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.AInstaller.<RecommendQueueSize>d__41.MoveNext() in d:\work\1\s\Wabbajack.Lib\AInstaller.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.MO2Installer.<_Begin>d__11.MoveNext() in d:\work\1\s\Wabbajack.Lib\MO2Installer.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<<Begin>b__44_0>d.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass27_1.<<-ctor>b__18>d.MoveNext()
82.94 - System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Wabbajack.Common.Utils.<TestDiskSpeed>d__76.MoveNext() in d:\work\1\s\Wabbajack.Common\Utils.cs:line 842
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<RecommendQueueSize>d__42.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.AInstaller.<RecommendQueueSize>d__41.MoveNext() in d:\work\1\s\Wabbajack.Lib\AInstaller.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.MO2Installer.<_Begin>d__11.MoveNext() in d:\work\1\s\Wabbajack.Lib\MO2Installer.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<<Begin>b__44_0>d.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass27_1.<<-ctor>b__18>d.MoveNext()
82.94 - Value cannot be null.
Parameter name: key - Can't continue
```

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by erri120** [comment]
Are you `Aughyssul` from Discord?

**Comment by LP0101** [comment]
Yup

**Comment by halgari** [comment]
Yep, I hit this on my local install as well, and never got around to fixing it. It's now fixed in master, and will be in the next beta, probably out later today.
