### ISSUE TITLE
Receiving a System.Collections.Generic.KeyNotFoundException during compile

### ISSUE THREAD

**Issue by jdsmith2816** [wabbajack-tools/wabbajack#421]
**Describe the bug**
During compile I receive the below exception

**Additional context**
Win10 Skyrim SE

**Logs**
```
318.6 - Removing 9 archives from the compilation state, this is probably not an issue but reference this if you have compilation failures
/* ... snip archive listing for brevity ... */
318.69 - Finding Install Files
337.92 - Compiler error - System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Wabbajack.Lib.MO2Compiler.<>c__DisplayClass53_0.<_Begin>b__6(String p) in d:\work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 162
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at Wabbajack.Common.Utils.<DistinctBy>d__67`2.MoveNext() in d:\work\1\s\Wabbajack.Common\Utils.cs:line 773
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wabbajack.Lib.MO2Compiler.<_Begin>d__53.MoveNext() in d:\work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.Lib.ABatchProcessor.<<Begin>b__49_0>d.MoveNext() in d:\work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.MO2CompilerVM.<Compile>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wabbajack.CompilerVM.<>c__DisplayClass63_0.<<-ctor>b__19>d.MoveNext()
```

**Solution**
Leave This blank, it will be filled in by the developers.

**Comment by halgari** [comment]
Should have been fixed as part of the server code rewrite for VFS downloading.
