### ISSUE TITLE
Wrap CEF initialization better

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#585]
Currently if CEF fails to load, it results in this stack trace:
```
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Wabbajack.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core, Version=79.1.350.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. An attempt was made to load a program with an incorrect format.
File name: 'CefSharp.Core, Version=79.1.350.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at Wabbajack.Lib.LibCefHelpers.Helpers.Init()
   at Wabbajack.Lib.LibCefHelpers.ModuleInitializer.Initialize() in c:\agent_work\1\s\Wabbajack.Lib\LibCefHelpers\Init.cs:line 104
   at .cctor()
```

Might be nice to:
- Not crash without displaying anything, but display some large error instead.
- Wrap the log message to suggest reinstalling C++ redists, which seems to be one of the potential fixes.. which will hopefully help people resolve the issue themselves, vs posting in discord

**Comment by erri120** [comment]
Can this be closed?
