### ISSUE TITLE
NullRef on Manual Downloading

### ISSUE THREAD

**Issue by Noggog** [wabbajack-tools/wabbajack#592]
Was just downloading various lists so that I can end up never playing any of them.

During Viva NV, I had a Manual Download come up.  Clicked most of the buttons I thought I should be clicking.  Install exited out as failed:
```
8354.84 - System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Lib.LibCefHelpers.Helpers.<>c__DisplayClass2_0.<GetCookies>b__0(Cookie c) in c:\agent\_work\1\s\Wabbajack.Lib\LibCefHelpers\Init.cs:line 47
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at Wabbajack.Lib.LibCefHelpers.Helpers.GetCookies(String domainEnding) in c:\agent\_work\1\s\Wabbajack.Lib\LibCefHelpers\Init.cs:line 47
   at Wabbajack.UserInterventionHandlers.HandleManualDownload(WebBrowserVM vm, CancellationTokenSource cancel, ManuallyDownloadFile manuallyDownloadFile) in c:\agent\_work\1\s\Wabbajack\View Models\UserInterventionHandlers.cs:line 146
   at Wabbajack.UserInterventionHandlers.WrapBrowserJob(IUserIntervention intervention, Func`3 toDo) in c:\agent\_work\1\s\Wabbajack\View Models\UserInterventionHandlers.cs:line 45
8354.85 - Encountered error, can't continue - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.ManualDownloader.State.Download(Archive a, String destination) in c:\agent\_work\1\s\Wabbajack.Lib\Downloaders\ManualDownloader.cs:line 85
   at Wabbajack.Lib.AInstaller.DownloadMissingArchives(List`1 missing, Boolean download) in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 248
   at Wabbajack.Lib.AInstaller.DownloadArchives() in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 241
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 97
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__49_0() in c:\agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 366
```

Seems to be a null ref on this line https://github.com/wabbajack-tools/wabbajack/blob/master/Wabbajack.Lib/LibCefHelpers/Init.cs#L47

Probably `c.Domain.EndsWith(...)` call?  Obviously I could just add a null check, but wanted to make sure that wasn't just a bandaid on the symptom first

**Comment by Noggog** [comment]
Eh, assign is a strong term, lol.  

Also wanted to note:  the logs didn't have much.  Just normal messages, and then the stack trace.  So not even sure what mod it was specifically

**Comment by halgari** [comment]
fixed in master (weeks ago)
