### ISSUE TITLE
Wabbajack unable to find a .tmp file in AppData

### ISSUE THREAD

**Issue by BraveeSnow** [wabbajack-tools/wabbajack#621]
Wabbajack is unable to compile a modlist due to a .tmp file not existing.

OS: Windows 10 1909 (Build 18363.657)
Game: Skyrim SE
Both MO2 and SSE is on my D: drive.

This is the main error it throws:
`Compiler error - System.IO.DirectoryNotFoundException: (3) The system cannot find the path specified: [C:\Users\brave\AppData\Local\Wabbajack\patch_cache\7865af8d-1a96-4674-aa5a-dfde2e7902b8.tmp]`

Here's my log:
```0.06 - Wabbajack Build - 037bef31c7adf2249af7a6a32ccc52e564c417be
0.34 - Wabbajack Version: 1.1.0.0
25.16 - Benchmarking D:\Wabbajack\1.1.0.0
46.19 - 674.4MB/sec for D:\Wabbajack\1.1.0.0
46.2 - Recommending a queue size of 6 based on disk performance, number of cores, and 15.8GB of system RAM
46.22 - Cleaning VFS, this may take a bit of time
46.27 - Gathering information
46.28 - Looking for other profiles
46.28 - Using Profiles: Legacy of the Dragonborn
46.29 - VFS File Location: C:\Users\brave\AppData\Local\Wabbajack\vfs_compile_cache-45b41b2c585d090aaa98ac2cb9e0c4171b9f81d2ec1f2e96bb953908cf8a1d62.bin
46.3 - Indexing folders
54.63 - Downloaded VFS data for zedit-water-damage-23254-1-0-1549573114.7z
54.88 - Downloaded VFS data for zedit-visual-transfer-23254-1-0-1-1549597958.7z
54.91 - Downloaded VFS data for zedit-spell-absorb-fix-23254-1-0-1550335188.7z
55.93 - Downloaded VFS data for Wrye Bash 307 Beta 5.1 - Standalone Executable-6837-307-beta5-1-1578493055.7z
58.32 - Downloaded VFS data for SSEEdit 4_0_3-164-4-0-3-1575326827.7z
59.95 - Downloaded VFS data for zEdit_v0.6.5_-_Portable_x64.7z
62.13 - Downloaded VFS data for oppositeAnimationDisabler-18281-1-1-2.zip
62.37 - Downloaded VFS data for skse64_2_00_17.7z
63.48 - Downloaded VFS data for Mator Smash Hotfix 2-90987-1-0-2.zip
67.36 - Downloaded VFS data for hishyNpcEnchantFix-13543-1-3-1551641676.zip
69.78 - Downloaded VFS data for hishy-khajiit-ears-show-13544-1-0.7z
69.79 - Downloaded VFS data for hishy-no-dragon-lods-13541-1-0.7z
70.25 - Downloaded VFS data for Mod Organizer 2 (Archive)-6194-2-2-2-1-1578979100.7z
70.91 - Downloaded VFS data for ExperiencePatcher-23589-1-1-1550763562.7z
71.6 - Downloaded VFS data for PapyrusAssembler.exe
71.64 - Downloaded VFS data for loot_0.15.1-0-g82c756e_master.7z
74.58 - Downloaded VFS data for CK64Fixes Release 2.7-20061-2-7-1579689332.zip
85.22 - Downloaded VFS data for Skyrim - Textures8.bsa
118.36 - Downloaded VFS data for Skyrim - Textures6.bsa
214.07 - Downloaded VFS data for Skyrim - Textures5.bsa
300.9 - Downloaded VFS data for Skyrim - Textures7.bsa
440.89 - Downloaded VFS data for Skyrim - Textures3.bsa
454.1 - Downloaded VFS data for Skyrim - Textures2.bsa
476.62 - Downloaded VFS data for Skyrim - Shaders.bsa
525.59 - Downloaded VFS data for Skyrim - Patch.bsa
536.9 - Downloaded VFS data for Skyrim - Textures0.bsa
558.88 - Downloaded VFS data for Skyrim - Textures4.bsa
574.5 - Downloaded VFS data for Skyrim - Misc.bsa
594.6 - Downloaded VFS data for Skyrim - Interface.bsa
628.22 - Downloaded VFS data for Skyrim - Animations.bsa
633.81 - The contents of D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Scripts.zip are being extracted to vfs_staging\5e85e695-ccd9-46bf-85bf-b2079cfc1429 using 7zip.exe
658.65 - Downloaded VFS data for Skyrim - Textures1.bsa
669 - Downloaded VFS data for Skyrim - Meshes1.bsa
871.41 - Downloaded VFS data for Skyrim - Sounds.bsa
910.78 - Downloaded VFS data for Skyrim - Meshes0.bsa
2299.16 - Extracting Scripts.zip - 100%
2457.74 - Downloaded VFS data for skse64_loader.exe
2458.27 - Downloaded VFS data for SkyrimSELauncher.exe
2459.06 - Downloaded VFS data for SkyrimSE.exe
2492.38 - Downloaded VFS data for lzma.exe
2492.41 - Downloaded VFS data for pngcrush.exe
2492.98 - Downloaded VFS data for 7z.exe
2495.21 - Downloaded VFS data for ArchiveInvalidationInvalidated!.bsa
2495.47 - Downloaded VFS data for ArchiveInvalidationInvalidated!.bsa
2495.49 - Downloaded VFS data for ArchiveInvalidationInvalidated!.bsa
2500.25 - Downloaded VFS data for elevate.exe
2502.74 - Downloaded VFS data for SSEDump.exe
2504.12 - Downloaded VFS data for Texconv.exe
2504.19 - Downloaded VFS data for Texconvx64.exe
2506.91 - Downloaded VFS data for SSEEdit64.exe
2507.34 - Downloaded VFS data for LODGenx64.exe
2507.44 - Downloaded VFS data for LODGen.exe
2508.22 - Downloaded VFS data for SSEDump64.exe
2511.98 - Downloaded VFS data for Skyrim.Hardcoded.dat
2512.09 - Downloaded VFS data for Oblivion.Hardcoded.dat
2512.61 - Downloaded VFS data for Fallout4.Hardcoded.dat
2512.67 - Downloaded VFS data for FalloutNV.Hardcoded.dat
2512.81 - Downloaded VFS data for Fallout3.Hardcoded.dat
2512.82 - Downloaded VFS data for icudtl.dat
2513.75 - Downloaded VFS data for Wrye Bash.exe
2513.78 - Downloaded VFS data for Skyrim.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat
2514.36 - Downloaded VFS data for Oblivion.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat
2514.99 - Downloaded VFS data for FalloutNV.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat
2515.46 - Downloaded VFS data for Fallout4.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat
2515.74 - Downloaded VFS data for MatorSmash.exe
2515.94 - Downloaded VFS data for Fallout3.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat
2516.01 - Downloaded VFS data for SSEEdit.exe
2516.14 - Downloaded VFS data for SSEEditQuickAutoClean.exe
2516.57 - Downloaded VFS data for LOOT.exe
2516.69 - Downloaded VFS data for icudtl.dat
2521.79 - Downloaded VFS data for cookies.dat
2525.42 - Downloaded VFS data for zEdit.exe
2531.1 - Downloaded VFS data for icudtl.dat
2532.11 - Downloaded VFS data for NexusClientCLI.exe
2532.2 - Downloaded VFS data for lootcli.exe
2532.73 - Downloaded VFS data for Explorer++.exe
2539.86 - Downloaded VFS data for zedit-spell-absorb-fix-23254-1-0-1550335188.7z
2540.23 - Downloaded VFS data for zedit-visual-transfer-23254-1-0-1-1549597958.7z
2540.25 - Downloaded VFS data for zedit-water-damage-23254-1-0-1549573114.7z
2542.73 - Downloaded VFS data for Wrye Bash 307 Beta 5.1 - Standalone Executable-6837-307-beta5-1-1578493055.7z
2543.47 - Downloaded VFS data for zEdit_v0.6.5_-_Portable_x64.7z
2547.83 - Downloaded VFS data for oppositeAnimationDisabler-18281-1-1-2.zip
2547.96 - Downloaded VFS data for skse64_2_00_17.7z
2547.98 - Downloaded VFS data for SSEEdit 4_0_3-164-4-0-3-1575326827.7z
2551.01 - Downloaded VFS data for Mator Smash Hotfix 2-90987-1-0-2.zip
2552.66 - Downloaded VFS data for Mod Organizer 2 (Archive)-6194-2-2-2-1-1578979100.7z
2555.33 - Downloaded VFS data for hishyNpcEnchantFix-13543-1-3-1551641676.zip
2555.35 - Downloaded VFS data for hishy-no-dragon-lods-13541-1-0.7z
2556.47 - Downloaded VFS data for loot_0.15.1-0-g82c756e_master.7z
2558.93 - Downloaded VFS data for hishy-khajiit-ears-show-13544-1-0.7z
2560.42 - Downloaded VFS data for ExperiencePatcher-23589-1-1-1550763562.7z
2561.1 - Downloaded VFS data for QtWebEngineProcess.exe
2561.1 - Downloaded VFS data for usvfs_proxy_x64.exe
2561.11 - Downloaded VFS data for usvfs_proxy_x86.exe
2561.51 - Downloaded VFS data for nxmhandler.exe
2561.7 - Downloaded VFS data for ModOrganizer.exe
2561.92 - Downloaded VFS data for helper.exe
2562.63 - Downloaded VFS data for CK64Fixes Release 2.7-20061-2-7-1579689332.zip
2567.84 - Downloaded VFS data for pythoncore.zip
2596.57 - Integrating 2785 files
2598.78 - Done integrating
2599.27 - Wrote 46.3MB file as vfs cache file C:\Users\brave\AppData\Local\Wabbajack\vfs_compile_cache-45b41b2c585d090aaa98ac2cb9e0c4171b9f81d2ec1f2e96bb953908cf8a1d62.bin
2599.92 - Cleaning output folder
2599.93 - Inferring metas for game file downloads
2601.62 - 
2691.73 - Reindexing downloads after meta inferring
2691.91 - Integrating 2785 files
2692.62 - Done integrating
2692.99 - Wrote 46.3MB file as vfs cache file C:\Users\brave\AppData\Local\Wabbajack\vfs_compile_cache-45b41b2c585d090aaa98ac2cb9e0c4171b9f81d2ec1f2e96bb953908cf8a1d62.bin
2693 - Pre-validating Archives
2693.16 - Checking link for zEdit_v0.6.5_-_Portable_x64.7z
2693.18 - Checking link for SSEEdit 4_0_3-164-4-0-3-1575326827.7z
2693.21 - Checking link for Wrye Bash 307 Beta 5.1 - Standalone Executable-6837-307-beta5-1-1578493055.7z
2693.22 - Checking link for zedit-visual-transfer-23254-1-0-1-1549597958.7z
2693.23 - Checking link for zedit-spell-absorb-fix-23254-1-0-1550335188.7z
2693.24 - Checking link for zedit-water-damage-23254-1-0-1549573114.7z
2693.59 - Checking link for Mod Organizer 2 (Archive)-6194-2-2-2-1-1578979100.7z
2693.6 - Checking link for skse64_2_00_17.7z
2693.61 - Checking link for oppositeAnimationDisabler-18281-1-1-2.zip
2693.61 - Checking link for Mator Smash Hotfix 2-90987-1-0-2.zip
2693.63 - Checking link for loot_0.15.1-0-g82c756e_master.7z
2693.9 - Checking link for hishyNpcEnchantFix-13543-1-3-1551641676.zip
2693.92 - Checking link for hishy-no-dragon-lods-13541-1-0.7z
2693.94 - Checking link for hishy-khajiit-ears-show-13544-1-0.7z
2694.07 - Checking link for ExperiencePatcher-23589-1-1-1550763562.7z
2694.2 - Checking link for CK64Fixes Release 2.7-20061-2-7-1579689332.zip
2694.65 - Finding Install Files
2694.97 - Found 2721 files to build into mod list
2694.98 - Verifying destinations
2695 - Loading INIs
2695.01 - Generating compilation stack
2695.14 - zEdit not detected, disabling zEdit routines
2695.15 - Running Compilation Stack
2695.55 - Adding 0 that were generated by the stack
2695.56 - No match for 0 files
2695.57 - Getting Nexus api_key, please click authorize if a browser window appears
2695.58 - Verifying Files
2695.58 - Gathering Archives
2695.59 - Building a list of archives based on the files required
2695.61 - Checking link for zedit-water-damage-23254-1-0-1549573114.7z
2695.61 - Checking link for oppositeAnimationDisabler-18281-1-1-2.zip
2695.62 - Checking link for zedit-spell-absorb-fix-23254-1-0-1550335188.7z
2695.63 - Checking link for zedit-visual-transfer-23254-1-0-1-1549597958.7z
2695.63 - Checking link for CK64Fixes Release 2.7-20061-2-7-1579689332.zip
2695.65 - Checking link for hishyNpcEnchantFix-13543-1-3-1551641676.zip
2695.9 - Checking link for hishy-no-dragon-lods-13541-1-0.7z
2695.91 - Checking link for hishy-khajiit-ears-show-13544-1-0.7z
2695.93 - Checking link for ExperiencePatcher-23589-1-1-1550763562.7z
2695.94 - Checking link for skse64_2_00_17.7z
2695.97 - Checking link for zEdit_v0.6.5_-_Portable_x64.7z
2696.05 - Checking link for Wrye Bash 307 Beta 5.1 - Standalone Executable-6837-307-beta5-1-1578493055.7z
2696.19 - Checking link for SSEEdit 4_0_3-164-4-0-3-1575326827.7z
2696.34 - Checking link for loot_0.15.1-0-g82c756e_master.7z
2696.35 - Checking link for Mator Smash Hotfix 2-90987-1-0-2.zip
2696.35 - Checking link for Mod Organizer 2 (Archive)-6194-2-2-2-1-1578979100.7z
2697.01 - Finding States to package
2697.26 - Packaging 16 inis
2698.16 - Including Archive Metadata
2698.17 - Including 16 .meta files for downloads
2698.69 - Building Patches
2698.71 - Gathering patch files
2698.73 - Patching building patches from 1 archives
2698.75 - The contents of D:\Mod Organizer 2\downloads\SSEEdit 4_0_3-164-4-0-3-1575326827.7z are being extracted to vfs_staging\70c523f7-f81e-4185-ac4b-40340a977209 using 7zip.exe
2703.25 - Extracting SSEEdit 4_0_3-164-4-0-3-1575326827.7z - 100%
2703.26 - Patching Game Folder Files\Tools\HavokBehaviorPostProcess\readme.txt
2704.5 - Compiler error - System.IO.DirectoryNotFoundException: (3) The system cannot find the path specified: [C:\Users\brave\AppData\Local\Wabbajack\patch_cache\7865af8d-1a96-4674-aa5a-dfde2e7902b8.tmp]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
   at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.CreateFileStreamCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.Create(String path)
   at Wabbajack.Common.Utils.CreatePatch(FileStream srcStream, String srcHash, FileStream destStream, String destHash, FileStream patchStream) in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 988
   at Wabbajack.Common.Utils.CreatePatch(FileStream srcStream, String srcHash, FileStream destStream, String destHash, FileStream patchStream) in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 1006
   at Wabbajack.Lib.MO2Compiler.<>c__DisplayClass57_1.<<BuildArchivePatches>b__4>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 460
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Lib.MO2Compiler.<>c__DisplayClass57_1.<<BuildArchivePatches>b__4>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 460
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Lib.MO2Compiler.<>c__DisplayClass57_1.<<BuildArchivePatches>b__4>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 460
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Lib.MO2Compiler.<>c__DisplayClass57_1.<<BuildArchivePatches>b__4>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 460
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Common.Utils.<>c__DisplayClass72_1`1.<<PMap>b__1>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 827
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, Func`2 f) in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 850
   at Wabbajack.Lib.MO2Compiler.BuildArchivePatches(String archiveSha, IEnumerable`1 group, Dictionary`2 absolutePaths) in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 451
   at Wabbajack.Common.Utils.<>c__DisplayClass72_1`1.<<PMap>b__1>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 827
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, Func`2 f) in T:\test-agent\_work\1\s\Wabbajack.Common\Utils.cs:line 850
   at Wabbajack.Lib.MO2Compiler.BuildPatches() in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 438
   at Wabbajack.Lib.MO2Compiler._Begin(CancellationToken cancel) in T:\test-agent\_work\1\s\Wabbajack.Lib\MO2Compiler.cs:line 281
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__49_0() in T:\test-agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 172
   at Wabbajack.MO2CompilerVM.Compile() in T:\test-agent\_work\1\s\Wabbajack\View Models\Compilers\MO2CompilerVM.cs:line 197
   at Wabbajack.CompilerVM.<>c__DisplayClass63_0.<<-ctor>b__19>d.MoveNext() in T:\test-agent\_work\1\s\Wabbajack\View Models\Compilers\CompilerVM.cs:line 188
```

I only have the creation kit installed, SKSE enabled and a few tools in the MO2 directory, which are:
- LOOT
- SSEEdit
- zEdit
- Wrye Bash
- Mator Smash

Everything needed is in the downloads folder as well.

**Comment by BraveeSnow** [comment]
Just tried a fresh install of SSE and the error seemed to disappear.

**Comment by BraveeSnow** [comment]
After getting the error message again, I got it to work by removing Tools\HavokBehaviorPostProcess\readme.txt within the SSE game directory.
