### ISSUE TITLE
Requires 'lovers lane' login to continue?

### ISSUE THREAD

**Issue by CrispyButtPhD** [wabbajack-tools/wabbajack#896]
**Describe the bug**
When I try to download 'Skrim VR Essentials' modlist, after logging into nexus premium account successfully, it then redirecs to a 'lovers lane' website. If i click back or exit, then in the log it says it fails because cookies from lovers lane website are not found. I.e. it is requiring me to join that website, which obviously no one would.
**Additional context**
Win 10
**Logs**

401.9 - Getting Nexus API Key, if a browser appears, please accept
401.91 - (Retry 1 of 5), got exception (2) The system cannot find the file specified: [C:\Users\patie\AppData\Local\Wabbajack\loverslabcookies], waiting 100ms
402.01 - (Retry 2 of 5), got exception (2) The system cannot find the file specified: [C:\Users\patie\AppData\Local\Wabbajack\loverslabcookies], waiting 200ms
402.22 - (Retry 3 of 5), got exception (2) The system cannot find the file specified: [C:\Users\patie\AppData\Local\Wabbajack\loverslabcookies], waiting 400ms
402.62 - (Retry 4 of 5), got exception (2) The system cannot find the file specified: [C:\Users\patie\AppData\Local\Wabbajack\loverslabcookies], waiting 800ms
403.42 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [C:\Users\patie\AppData\Local\Wabbajack\loverslabcookies], waiting 1600ms
405.03 - Getting Lovers Lab Login
415.92 - Encountered error, can't continue - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.AbstractNeedsLoginDownloader.GetAuthedClient() in C:\agent\_work\1\s\Wabbajack.Lib\Downloaders\AbstractNeedsLoginDownloader.cs:line 100
   at Wabbajack.Lib.Downloaders.AbstractNeedsLoginDownloader.Prepare() in C:\agent\_work\1\s\Wabbajack.Lib\Downloaders\AbstractNeedsLoginDownloader.cs:line 107
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 239
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 117
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__46_0() in C:\agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 164
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in C:\agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 364

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/4707147/Wabbajack.current.log)

Please add your `Wabbajack.exe.log` file or the complete stack trace of your error to this report. Refere to [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) page if you do not know how to post the stack trace in a code block.

**Comment by halgari** [comment]
Please join the discord for the site and take this up with the list maintainer. This is not a bug.
