### ISSUE TITLE
Wabbajack failing to extract archive due to Japanese character in filename

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack#918]
**Describe the bug**
Someone in the Living Skyrim support channel was trying to install it, but kept running into an issue where an archive couldn't be extracted, probably due to the fact there was a Japanese character in the file.

**Logs**
```85.75 - Hashing Archives
85.75 - Looking for files to hash
85.9 - Found 1653 files to hash
86.61 - Downloading Missing Archives
86.61 - Missing 0 archives
86.61 - Getting Nexus API Key, if a browser appears, please accept
86.61 - Hashing Remaining Archives
86.61 - Looking for files to hash
86.62 - Found 1653 files to hash
86.76 - Extracting Modlist contents
86.77 - The contents of Living Skyrim 2 Beta 4 .wabbajack are being extracted to Living Skyrim 2 Beta 4 .wabbajack using 7zip.exe
103.01 - Extracting Living Skyrim 2 Beta 4 .wabbajack - done
103.04 - Priming VFS
103.16 - Integrating 1648 files
103.18 - Done integrating
103.18 - Building Folder Structure
103.18 - Building Folder Structure
103.25 - Installing Archives
103.25 - Installing Archives
103.25 - Grouping Install Files
103.25 - Installing Archives
103.35 - The contents of Rayek's End - SSE Expanded Edition 1.7-8285-1-7.zip are being extracted to Rayek's End - SSE Expanded Edition 1.7-8285-1-7.zip using 7zip.exe
104.62 - Extracting Rayek's End - SSE Expanded Edition 1.7-8285-1-7.zip - done
104.73 - Encountered error, can't continue - System.Collections.Generic.KeyNotFoundException: The given key 'Meshes\Oaristys\Clutter\Mirror°.nif' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Wabbajack.VirtualFileSystem.Context.Stage(IEnumerable`1 files) in c:\agent\_work\1\s\Wabbajack.VirtualFileSystem\Context.cs:line 221
   at Wabbajack.Lib.AInstaller.InstallArchive(WorkQueue queue, Archive archive, AbsolutePath absolutePath, IGrouping`2 grouping) in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 140
   at Wabbajack.Common.Utils.<>c__DisplayClass103_0`1.<<PMap>b__0>d.MoveNext() in c:\agent\_work\1\s\Wabbajack.Common\Utils.cs:line 501
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Common.Utils.<>c__DisplayClass107_1`1.<<PMap>b__1>d.MoveNext() in c:\agent\_work\1\s\Wabbajack.Common\Utils.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, Func`2 f) in c:\agent\_work\1\s\Wabbajack.Common\Utils.cs:line 642
   at Wabbajack.Common.Utils.PMap[TI](IEnumerable`1 coll, WorkQueue queue, StatusUpdateTracker updateTracker, Func`2 f) in c:\agent\_work\1\s\Wabbajack.Common\Utils.cs:line 498
   at Wabbajack.Lib.AInstaller.InstallArchives() in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 126
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 148
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__46_0() in c:\agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 168
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 159
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 363```

**Comment by tr4wzified** [comment]
Relevant mod: https://www.nexusmods.com/skyrimspecialedition/mods/8285?tab=files

**Comment by erri120** [comment]
Same as #903
